### ISSUE TITLE
Guard uses inotify_add_watch on ignored directories

### ISSUE THREAD

**Issue by aletessier** [guard/guard#320]
Guard is using inotify_add_watch even on directories which are ignored. The following example shows how to reproduce the behavior. My problem is that i would like to use guard on a directory with many subdirectories and my SSD is going crazy because of this. Is there something wrong in my config?

```
~/t/guard % tree
.
├── file
├── Guardfile
└── toto
    └── titi
        └── file

2 directories, 3 files

~/t/guard % cat Guardfile 

ignore %r{toto/}

guard :shell do
  watch 'file' do |m|
    n m[0], 'changed'
  end
end

~/t/guard % strace -e inotify_add_watch guard   
Guard uses Libnotify to send notifications.
Guard is now watching at '/home/alex/Tools/guard'
> inotify_add_watch(3, "/home/alex/Tools/guard/toto/titi", IN_ATTRIB|IN_CLOSE_WRITE|IN_MOVED_FROM|IN_MOVED_TO|IN_CREATE|IN_DELETE) = 1
inotify_add_watch(3, "/home/alex/Tools/guard/toto", IN_ATTRIB|IN_CLOSE_WRITE|IN_MOVED_FROM|IN_MOVED_TO|IN_CREATE|IN_DELETE) = 2
inotify_add_watch(3, "/home/alex/Tools/guard", IN_ATTRIB|IN_CLOSE_WRITE|IN_MOVED_FROM|IN_MOVED_TO|IN_CREATE|IN_DELETE) = 3
inotify_add_watch(4, "/home/alex/Tools/guard/toto/titi", IN_ATTRIB|IN_CLOSE_WRITE|IN_MOVED_FROM|IN_MOVED_TO|IN_CREATE|IN_DELETE) = 1
inotify_add_watch(4, "/home/alex/Tools/guard/toto", IN_ATTRIB|IN_CLOSE_WRITE|IN_MOVED_FROM|IN_MOVED_TO|IN_CREATE|IN_DELETE) = 2
inotify_add_watch(4, "/home/alex/Tools/guard", IN_ATTRIB|IN_CLOSE_WRITE|IN_MOVED_FROM|IN_MOVED_TO|IN_CREATE|IN_DELETE) = 3

```

**Comment by DreadPirateShawn** [comment]
As a note for posterity -- a `directories` feature was added in [guard v2.9.0](https://github.com/guard/guard/releases/tag/v2.9.0), which allows you to add a line like `directories %w(app lib config test spec)` to your Guardfile, omitting any directory not specified. (Note: Though support was added in 2.9.0, I'm currently using the latest release 2.13.0, so there may be important fixes between .9 and .13.)

This is perfect for the original issue above (top-level "toto" directory), or for ignoring the "public" directory, etc.

This avoids the main problem with the original solution suggested above, namely that increasing the inotify watchers to 524288 may prevent a crash, but it still performs abysmally.

Note that this is basically an official implementation of the Listen option two comments above.
