### ISSUE TITLE
Disable tmux notifications

### ISSUE THREAD

**Issue by jonaustin** [guard/guard#363]
There doesn't seem to be any way to disable tmux notifications?
(I want other notifications (e.g. libnotify), but not tmux)

i.e.  Guardfile:

```
notification :tmux,
  :enable => false
```

**Comment by sammilechman** [comment]
If you're just looking to disable tmux notifications without enabling another type:
```
notification :tmux,
  color_location: []
```

**Comment by tonatiuh** [comment]
Awesome, thanks @sammilechman!
