### ISSUE TITLE
Add option to disable certain notifications

### ISSUE THREAD

**Issue by diasjorge** [guard/guard#446]
Hi,

I'd like to be able to stop guard from trying to send me notifications via emacs, I still want to use terminal-notifier though.

I haven't found any way to do this so I've resorted to this hack

```
Notifier::NOTIFIERS = [
  [
    [:terminal_notifier, ::Guard::Notifier::TerminalNotifier],
  ],
  [[:terminal_title,    ::Guard::Notifier::TerminalTitle]],
]
```

Am I missing something? Any ideas?

**Comment by axilleas** [comment]
In case someone arrives here, I added some info in the wiki https://github.com/guard/guard/wiki/System-notifications#disabling-notifications
