### ISSUE TITLE
Typing doesn't appear in terminal after exiting guard

### ISSUE THREAD

**Issue by mockdeep** [guard/guard#619]
I've been running into this strange behavior for a while. I'll exit guard with `ctrl+D` and when I get a bash prompt, nothing appears at the prompt when I type. I can type shell commands and they will execute, but no text appears as I type. The output from the commands typed does show up. Using `GNU bash, version 4.2.25(1)-release (x86_64-pc-linux-gnu)`.

**Comment by bf4** [comment]
So, I see in the docs https://github.com/guard/guard/wiki/Add-Readline-support-to-Ruby-on-Mac-OS-X the `.editrc` fix I mentioned isn't there. I looked for it in the history, and it turns out it was in the [Pry Docs](https://github.com/pry/pry/wiki/FAQ#how-can-i-get-readline-support-ctrlr-etc-for-pry-in-osx)

> ### How can I get readline support (ctrl+r etc) for Pry in OSX?
> Technically for OSX you don't need readline, and we'll focus on using libedit which OSX comes with instead.

> Edit the file `.editrc` in your home directory. Add this line:
> ```
> bind "^R" em-inc-search-prev
> ```

> You can now use ctrl+r to do a reverse history search.

> Ref: http://hints.macworld.com/article.php?story=20080313113705760

> Alternatively, install GNU Readline and get Ruby to use it: https://github.com/guard/guard/wiki/Add-Readline-support-to-Ruby-on-Mac-OS-X

> Finally, Pry does work with rb-readline, a pure Ruby implementation of Readline which shouldn't suffer from the platform and install dependencies of the standard Readline.
> Ref: https://github.com/luislavena/rb-readline

It seems these docs talk to each other. May I add the editrc info or link to the pry docs?

**Comment by e2** [comment]
@bf4 -
> May I add the editrc info or link to the pry docs?
Absolutely! It would be much appreciated!

**Comment by rahilsondhi** [comment]
I have this problem too. Even after a fresh restart, I'm using spring+guard, when I put a binding.pry breakpoint in my code, I cannot see anything I type. I tried adding `bind "^R" em-inc-search-prev` to `~/.editrc` and restarted my terminal but that did not help.

**Comment by bf4** [comment]
@rahilsondhi `export DISABLE_SPRING=1` and all your troubles will go away

**Comment by rahilsondhi** [comment]
Thanks. I tried putting that in my terminal before starting guard - no
dice. I even removed spring from my Guardfile, no dice.
