### ISSUE TITLE
Is there a way to run guard together with an Rails app?

### ISSUE THREAD

**Issue by brauliobo** [guard/guard#628]
One thing that makes me wonder is why I have to run guard as a daemon if I'm already running the rails server as a daemon. For me, it makes sense to have guard running toghether with the rails application.

I just read the documentation at https://github.com/guard/guard/wiki/Use-Guard-programmatically-cookbook and I'm wondering if I just need to run it in a `Thread` or `fork`, inside the rails' `config/application.rb`.

Would it work?

**Comment by gustavovendramini** [comment]
@brauliobo For me it was necessary to require commander. Using guard 2.13.0 and guard-rake 1.0.0

```
require "guard/commander"
```

**Comment by havran** [comment]
I'm try runing rails rake task like rake db:migrate:status and Guard always started. Then i make this:

``` ruby
require 'guard'
require 'guard/commander'

fork do
  if __FILE__ == '(irb)'
  end

  Guard.start :no_interactions => true
end if File.basename($0, '.*') == 'rails'
```

But i still don't understand meanig of if __FILE__ == '(irb)'  end part of code? Probably more examples should be useful for this usage. 

Thanks.

**Comment by e2** [comment]
@havran - probably a leftover from something else. Feel free to remove and update the example in the Wiki.

You can put the `if File.(...)` around the `fork do` for clarity - and just comment that it's for `db:migrate:status`.
