### ISSUE TITLE
Stop hook is not called

### ISSUE THREAD

**Issue by manuelmeurer** [guard/guard#669]
After reading the [wiki page for hooks](https://github.com/guard/guard/wiki/Hooks-and-callbacks), where it says

> By default, each of the Guard instance methods has a "_begin" and an "_end" hook."

I thought I could use `stop_begin` (or `stop_end`) just like `start_begin` in the examples. It doesn't work though, the hook is never called.

``` ruby
class Guard::StartHook
  def call(guard_class, event, *args)
    puts guard_class
    puts event
    puts args
  end
end

class Guard::StopHook
  def call(guard_class, event, *args)
    sleep 5
    puts guard_class
    puts event
    puts args
  end
end

guard 'rspec', cmd: 'bundle exec rspec' do
  # This works
  callback StartHook.new, :start_begin

  # Neither of these work
  callback StopHook.new, :stop
  callback StopHook.new, :stop_begin
  callback StopHook.new, :stop_end
end
```

I found #664 and thought this would be the same bug, but I'm already using v2.8.2 in which the bug was fixed...

**Comment by binarymason** [comment]
@e2 Looks like the monkey patch works for `run_on_modifications_end`... but only if the tests pass.  I'm guessing if the tests exit non-zero the monkey patch never gets executed.

Any idea how to get around this?
