### ISSUE TITLE
Guard.options is gonne?

### ISSUE THREAD

**Issue by nofxx** [guard/guard#684]
The example .guardrc:

```
Guard.options[:clear] = true
```

Gives:

```
when_started hook failed: NoMethodError: undefined method `options' for Guard:Module
```

And it doesn't clear.  Thanks in advance.

**Comment by newdark** [comment]
I know you added the clearing ability to the guard file however there is no documentation on how to do this in the ~/.guardrc file where it currently works.

**Comment by newdark** [comment]
Here is the error I get when I try to use clearing :on in the ~/.guardrc
```ruby
when_started hook failed: NoMethodError: undefined method `clearing' for main:Object
/Users/newdark/.guardrc:9:in `<top (required)>'
(see _pry_.hooks.errors to debug)
```

**Comment by e2** [comment]
> there is no documentation on how to do this in the ~/.guardrc

@newdark - thanks for letting me know!

It's a bit confusing, I guess.  The `~/.guardrc` is only for the Pry interactor. What you're looking for is the `~/.guard.rb` file, where you can use DSL statements just like in the Guardfile.

I've added this Wiki entry: https://github.com/guard/guard/wiki/Configuration-files.

And I've mentioned the `~/.guard.rb` file here: https://github.com/guard/guard/wiki/Guardfile-DSL---Configuring-Guard

Let me know if you have suggestions on documenting that better.

Thanks!

**Comment by newdark** [comment]
ok good to know that the ~/.guard.rb file will do what I need. I was wondering however it says to add clearing :on and I have been trying to use it however it seams to have no effect on the terminal. I have just followed the Guard file instructions but it does not seam to work. 

```ruby
## Uncomment to clear the screen before every task
clearing :on
```

**Comment by e2** [comment]
@newdark - I'll fix this soon, see: #710

**Comment by e2** [comment]
@newdark - fixed on master - will be included in next release.

Thanks for reporting this!

**Comment by squarism** [comment]
Fantastic.  Works since Guard 2.10 then.  For those wondering putting `clearing :on` outside any guard statements (like at the top of the `Guardfile`) will enable this.  I can stop typing "... guard -c" now.  Yay!

**Comment by newdark** [comment]
Thanks for the help on this really appreciate the work :smile:

**Comment by e2** [comment]
@newdark - thanks for letting me know. I try to test as much as possible and cover everything with tests - but there's always something I miss that I often never even knew about.

@squarism - things like `clearing` and `notification` should go into a `~/.guard.rb` file, because they are mostly user-specific settings. Do let me know if stuff like that doesn't work as expected - if there isn't an open bug for something, I likely have no idea people are even having a problem.

Glad to help!

**Comment by squarism** [comment]
Ok good to know.  I used to put those settings in .guardrc but then got a deprecation warning saying that those options are "best to be set in guard_options".  I guess this is an odd legacy edge case maybe where I had a really old `.guardrc` file.
