### ISSUE TITLE
regression: `clearing :on` doesn't work anymore

### ISSUE THREAD

**Issue by e2** [guard/guard#710]
Using `clearing: on` in `~/.guard.rb` doesn't work since: https://github.com/guard/guard/commit/871207c36f67b0bdf39168130b167ac6cb36ca2d

(since getting old hack to work: https://github.com/guard/guard/issues/684#issuecomment-68801739)

**Comment by mcandre** [comment]
Which published version of guard offers `clearing: on` in `~/.guard.rb`?

**Comment by e2** [comment]
@mcandre - use the latest version of Guard. If something doesn't work there, report a bug.

Otherwise I always list the bugs in the releases, so it's here: https://github.com/guard/guard/releases/tag/v2.11.0
