### ISSUE TITLE
Guard gem doesn't run on windows?

### ISSUE THREAD

**Issue by trekr5** [guard/guard#717]
Hi,

I've installed the guard ruby gem version 2.11.1 on windows and have attempted to create the Guardfile running the guard init command. 

I get the following error:

bundle exec guard init
bundler: command not found: guard
Install missing gem executables with 'bundle install'

I have already ran bundle install with no problems after adding the guard gem to the GemFile and it has downloaded the relevant dependencies as well..

C:\git\GG.Infra.UserManager>bundle install
Resolving dependencies...
Using rake 10.4.2
Using bundler 1.7.6
Using hitimes 1.2.2
Using timers 4.0.1
Using celluloid 0.16.0
Using coderay 1.1.0
Using daemons 1.1.9
Using diff-lcs 1.2.5
Using eventmachine 1.0.3
Using ffi 1.9.6
Using formatador 0.2.5
Using gginfrausermanager 0.1.0 from source at .
Using rb-fsevent 0.9.4
Using rb-inotify 0.9.5
Using listen 2.8.5
Using lumberjack 1.0.9
Using nenv 0.1.1
Using shellany 0.0.1
Using notiffany 0.0.2
Using method_source 0.8.2
Using slop 3.6.0
Using win32console 1.3.2
Using pry 0.10.1
Using thor 0.19.1
Using guard 2.11.1
Using net-ldap 0.10.1
Using rack 1.6.0
Using rack-protection 1.5.3
Using rspec-support 3.1.2
Using rspec-core 3.1.7
Using rspec-expectations 3.1.2
Using rspec-mocks 3.1.3
Using rspec 3.1.0
Using tilt 1.4.1
Using sinatra 1.4.5
Using thin 1.6.3
Using win32-service 0.8.6
Your bundle is complete!
Use `bundle show [gemname]` to see where a bundled gem is installed.

C:\git\GG.Infra.UserManager>bundle exec guard init
bundler: command not found: guard
Install missing gem executables with `bundle install`

C:\git\GG.Infra.UserManager>gem list guard
guard (2.11.1)

Can you tell me how to get the guard gem running correctly on windows?

Thanks

**Comment by e2** [comment]
That's a very strange error you're getting.

1. Try `bundle binstub guard` if bundle can find the file.
2. Try `gem install guard` and then `guard` (without bundle exec) to see if you get an error (you shouldn't)
3. Do other bins from other gems work? (try `bundle exec thin` for example)
4. What does `bundle show guard` say?
5. Make sure there's a `bin/guard` listed after running `bundle exec gem contents guard`

Anyway, this is really strange issue your having - could be a problem with your Ruby setup and or $PATH environment variable.

**Comment by e2** [comment]
Closing this - please reopen if you still have the issue.
