### ISSUE TITLE
Readline problem on Mac OS X Yosemite + RVM

### ISSUE THREAD

**Issue by xuhaoatwelab** [guard/guard#719]
At first I begin to use guard, I noticed the wiki [Add Readline support to Ruby on Mac OS X](https://github.com/guard/guard/wiki/Add-Readline-support-to-Ruby-on-Mac-OS-X) and I did the **Using RVM** way.

My env:
```
Mac OS X Yosemite + RVM + ruby 2.2.0,  I also use homebrew.
```

But I still have same problem mentioned [here](http://benlimmer.com/2014/03/31/guard-plus-pry-mac/):
```
I noticed that what I was typing was not being echoed to the screen. I could still execute commands, but I couldn’t see what I was typing. Pretty annoying!
```

Then I tried to add `rb-readline` gem, problem still there.
Then I tried the **Using rbenv, ruby_build and Homebrew** way mentioned in Wiki, problem still there.
Then I tried to switch to ruby 2.1.5 with **Using RVM** way, problem still there.

Is anyone got same problem before? it's a bug or my mistake for using?

**Comment by e2** [comment]
What gems are you using? (E.g. guard-zeus causes that problem).

Do you have the problem with an "empty"/"minimal" project?

You can check the readline version used by Pry under Guard by typing in: `Readline::VERSION`.

**Comment by xuhaoatwelab** [comment]
@e2 used gems related to guard:
```
  gem 'guard-rspec', require: false
  gem 'guard-zeus'
  gem 'guard-bundler', require: false
  gem 'guard-annotate'
  gem 'guard-livereload', require: false
  gem 'rack-livereload'
```
Readline version:
```
[1] guard(main)> Readline::VERSION
=> "5.2"
```

I did not test in "empty"/"minimal" project yet.

**Comment by e2** [comment]
guard-zeus is causing the problem (see guard-zeus/zeus issues opened by me).

Personally, I run guard-zeus in a separate window. Other people use Spring.

**Comment by e2** [comment]
see: https://github.com/guard/guard-zeus/issues/18

(There's a workaround using /dev/null if it works - though all zeus errors would be silenced)

**Comment by xuhaoatwelab** [comment]
@e2, Thanks! workaround works for me.

**Comment by e2** [comment]
Glad to help.

I updated the Wiki too - it's not the first time someone had the problem because of guard-zeus.

**Comment by xuhaoatwelab** [comment]
Thanks again for help on this issue. And thanks for your work on Gurad and Guard plugins, good job!

**Comment by deivid-rodriguez** [comment]
Hi, this problem seems to be happening all around... I guess it's a problem in readline or how people is using it. Just adding some links in here for completeness...

deivid-rodriguez/byebug#63
deivid-rodriguez/byebug#59
pry/pry/#1183
pry/pry/#1275
pry/pry/#1290
