### ISSUE TITLE
How do I change the watching and refresh rate speed really fast?

### ISSUE THREAD

**Issue by joowh85** [guard/guard#723]
How do I change the watching and refresh rate speed really fast?

**Comment by e2** [comment]
Check out the performance section of Listen (which guard uses): https://github.com/guard/listen#performance

Especially, the `LISTEN_GEM_DEBUGGING=2` environment variable will show the timings of events from OS and including the callback time.

There are a lot of factors at play here - so it depends on your project/setup/os/filesystem/editor/plugins/CPU/hard drive/etc.

**Comment by e2** [comment]
The listen options which can be set from Guard are here: https://github.com/guard/guard/wiki/Command-line-options-for-Guard#listen-options

**Comment by joowh85** [comment]
Thanks..  It's useful.
