### ISSUE TITLE
cannot add guard to empty Guardfile

### ISSUE THREAD

**Issue by e2** [guard/guard#730]
Error: `lib/guard/guardfile/evaluator.rb:88:in `evaluate': No Guard plugins found in Guardfile, please add at least one. (Guard::Guardfile::Evaluator::NoPluginsError)`

How to reproduce:
1. add only `guard` to `Gemfile`
2. `guard init`
3. add a guard plugin to `Gemfile`, e.g. `guard-rspec`
4. `guard init rspec` # => fails

**Comment by zoras** [comment]
@e2 can you check the pull request. It fixes the issue but I'm not sure if I'm doing it the right way.

**Comment by e2** [comment]
I forgot about this issue and fixed it here: https://github.com/guard/guard/pull/766

(Instead of checking the Guardfile itself, it checks for existing plugins using the DslReader class)
