### ISSUE TITLE
uninitialized variable in class `Notifier`

### ISSUE THREAD

**Issue by mblumtritt** [guard/guard#742]
Because of the variable `@notifier` is not initialized for `Guard::Notifier` Ruby warns on access in lib/guard/notifier.rb at line 27 (https://github.com/guard/guard/blob/master/lib/guard/notifier.rb#L27). This may confusing when e.g. running tests.

To initialize the variable correctly will also fix the glitches at https://github.com/guard/guard/blob/master/lib/guard/notifier.rb#L7.

**Comment by e2** [comment]
`Guard::Notifier.connect()` should be called to correctly initialize the variable first.

I think some plugins may be calling the `notify()` without connect, but I can't remember the exact scenarios.

If this is a problem, could you create a small repo reproducing the warning? (Along with the command you use). It could be a bug somewhere else.

**Comment by traceyn** [comment]
There is a reference to 'notifier' at line 35 that should be '@notifier' https://github.com/guard/guard/blob/master/lib/guard/notifier.rb#L35. Although this will still fail if @notifier is not initialized

**Comment by e2** [comment]
Thanks @traceyn!

Fixed on master.
