### ISSUE TITLE
Bundle Exec Guard Command Not Working

### ISSUE THREAD

**Issue by serg-gomez** [guard/guard#748]
I have just installed ruby via ruby installer 1.9.3-p551 required for drupal omega 4 theming.
I have installed drush and it is working.
I installed bundle and ran bundle install for dependencies - all dependencies installed and met.
Yet when I use command:
"bundle exec guard"
nothing happens.   I just get another command prompt.  No errors either.
I tried running"drush omega-guard"  with same results.
I tried running "bundle exec guard -d" same results, just another command prompt
 
I'm on a windows 7 machine.
ruby 1.9.3-p551 with devkit
using Pik for ruby management

Not sure what to do.  Need help figuring this out.

**Comment by e2** [comment]
> I just get another command prompt

If the prompt looks something like this:
```
[1] guard(main)>
```

Then it means guard is working (it's waiting for changes in files).
If you type in `show` it should show you a list of Guard plugins (e.g. including Livereload).

Try changing an *.scss file and see if anything in the output changes.

**Comment by serg-gomez** [comment]
nope, the command prompt is the same as before I executed "bundle exec guard"
I'm executing the command from this path.
H:\Uwamp\www\sunriserealty\sites\all\themes\sunrise_v1>

Executing the command:
H:\Uwamp\www\sunriserealty\sites\all\themes\sunrise_v1>bundle exec guard

H:\Uwamp\www\sunriserealty\sites\all\themes\sunrise_v1>

**Comment by serg-gomez** [comment]
ok, I tried starting from scratch. I deleted all gems.  installed bundler (1.8.2), then ran 'bundle install" which completed - no errors.  When I run 'bundle exec guard'  i get the following error:

H:\UwAmp\www\sunriserealty\sites\all\themes\sunrise_v1>bundle exec guard
Y:/WebDevStack/Ruby193/lib/ruby/gems/1.9.1/gems/guard-2.12.2/bin/guard:18:in `sp
awn': Exec format error - Y:/WebDevStack/Ruby193/lib/ruby/gems/1.9.1/gems/guard-
2.12.2/bin/_guard-core (Errno::ENOEXEC)
        from Y:/WebDevStack/Ruby193/lib/ruby/gems/1.9.1/gems/guard-2.12.2/bin/gu
ard:18:in `ignore_interrupts'
        from Y:/WebDevStack/Ruby193/lib/ruby/gems/1.9.1/gems/guard-2.12.2/bin/gu
ard:27:in `<top (required)>'
        from Y:/WebDevStack/Ruby193/bin/guard:23:in `load'
        from Y:/WebDevStack/Ruby193/bin/guard:23:in `<main>'

H:\UwAmp\www\sunriserealty\sites\all\themes\sunrise_v1>

Not sure what it means and how to troubleshoot it.

**Comment by serg-gomez** [comment]
Contents of Gemfile:  (Created by Drupal Omega 4 Subtheme):

source 'https://rubygems.org'

group :development do

  # Sass, Compass and extensions.
  gem 'sass'                    # Sass.
  gem 'sass-globbing'           # Import Sass files based on globbing pattern.
  gem 'compass'                 # Framework built on Sass.
  gem 'compass-validator'       # So you can `compass validate`.
  gem 'compass-normalize'       # Compass version of normalize.css.
  gem 'compass-rgbapng'         # Turns rgba() into .png's for backwards compatibility.
  gem 'susy'                    # Susy grid framework.
  gem 'singularitygs'           # Alternative to the Susy grid framework.
  gem 'toolkit'                 # Compass utility from the fabulous Snugug.
  gem 'breakpoint'              # Manages CSS media queries.
  gem 'oily_png'                # Faster Compass sprite generation.
  gem 'css_parser'              # Helps `compass stats` output statistics.

  # Guard
  gem 'guard'                   # Guard event handler.
  gem 'guard-compass'           # Compile on sass/scss change.
  gem 'guard-shell'             # Run shell commands.
  gem 'guard-livereload'        # Browser reload.
  gem 'yajl-ruby'               # Faster JSON with LiveReload in the browser.

  # Dependency to prevent polling. Setup for multiple OS environments.
  # Optionally remove the lines not specific to your OS.
  # https://github.com/guard/guard#efficient-filesystem-handling
  gem 'rb-inotify', '~> 0.9', :require => false      # Linux
  gem 'rb-fsevent', :require => false                # Mac OSX
  gem 'rb-fchange', :require => false                # Windows

end

**Comment by e2** [comment]
> spawn': Exec format error - Y:/WebDevStack/Ruby193/lib/ruby/gems/1.9.1/gems/guard- 2.12.2/bin/_guard-core

That's actually all I needed.

I just fixed this and it should work in Guard version 2.12.3 (run `bundle update guard` to update to this new version). 

If it still doesn't work, just paste the output like above (I don't use Windows, but years ago you could set the "window" width size in the command window preferences - which makes copying text from the console much easier).

**Comment by serg-gomez** [comment]
Thank you very much!  Guard is now watching!!!   I couldn't update guard to version 2.12.3, so to start fresh, I removed all gems, installed bundler and ran "bundle install".

**Comment by e2** [comment]
Thanks for taking the time to report the issue.

Also, there's usually no reason to start fresh - most things can be fixed one way or another without doing drastic things. Did bundler complain about upgrading? What kind of error did you get?

**Comment by serg-gomez** [comment]
Not sure about the error. But the update did not go through.  Have been trying to get my sass going for over 3 days with errors.  It was just easier to remove gems and run bundle install to get them back.
