### ISSUE TITLE
--listen-on does not work in vagrant guest in versions > 2.6.1

### ISSUE THREAD

**Issue by jschroeder9000** [guard/guard#751]
Using an Ubuntu 14.04 vagrant guest and Kubuntu 14.04 host, I have not been able to get guard's --listen-on option to work correctly in versions `> 2.6.1`.

```bash
listen -f 10.11.12.1:4000 # on the host
guard -o 10.11.12.1:4000 -w "/home/me/my_project" # on the guest
```

```ruby
# works
gem 'guard', '2.6.1'
gem 'listen', '2.8.6'
gem 'guard-rspec', '4.2.8'

# does not work
gem 'guard', '2.7.0'
gem 'listen', '2.8.6'
gem 'guard-rspec', '4.2.8'
```

With `guard > 2.6.1`, nothing happens on the guest when a file changes.  With `guard >= 2.5.1` and `<= 2.6.1`, everything works as expected.  Weirdly, running `guard` with `-o` on the **host** _does_ seem to work in `> 2.6.1`.

See also:  http://stackoverflow.com/q/28754943/4283486

**Comment by e2** [comment]
Thanks for reporting this!

The `-w` option changed behavior in 2.7.0 (it's behavior was considered buggy, misleading and useless).

In short, as long as the paths match on the host and guest, you don't need the `-w "/home/me/my_project"` - it should work if you simply run `guard -o 10.11.12.1:4000` in the project directory (`guard` makes paths relative to current directory automatically).

If you DON'T have a matching directory, `Guard` tries to map the path relative to the current, like this (given you are in e.g. `/home/user2/my_project_copy`):

```ruby
Pathname("/home/user/my_project/foo.txt").relative_path_from(Pathname.pwd).to_s
=> "../../../home/user/my_project/foo.txt"
```

Currently to get this to work, you'd have to change your rules in the `Guardfile` - which is probably not what you want, e.g.:

```ruby
guard :foo do
  # without a regexp to get the point
  watch('../../../home/user/my_project') { |m| m.sub('../../../home/user/my_project/','') }
end
```

Currently, I'm not sure how to fix this.

**Comment by e2** [comment]
There should be e.g. a `:relative` option in Listen for TCP: https://github.com/guard/listen/issues/297

Add a comment there so you're notified as soon as there's a fix and release with the fix (I'll try and fix it as soon as I can - maybe after a day or two).

I'm surprised no one reported this up till now.

**Comment by e2** [comment]
The expected solution (once implemented in Listen) will need:

```bash
listen -r -f 10.11.12.1:4000 # on the host (note "-r" option)
guard -o 10.11.12.1:4000 # on the guest (paths will be relative, so they should match rules without any problems)
```

**Comment by e2** [comment]
@jschroeder9000 - if you're in a hurry, you can locally patch Listen (on the host) by changing `dir` to `Pathname('.')` on this line: https://github.com/guard/listen/blob/master/lib/listen/listener.rb#L174

**Comment by e2** [comment]
@jschroeder9000 - Listen 2.9.0 is released with the `-r` (`--relative`) option (I've updated the README here: https://github.com/guard/listen#forwarding-file-events-over-tcp).

Let me know if you have other issues.

If you can, comment on articles/tutorial that you used or found - about the correct usage for guard >= 2.7.0. Thanks!

**Comment by jschroeder9000** [comment]
Will do, thanks for getting this sorted so quickly!
