### ISSUE TITLE
error: "hw.ncpu" is an unknown key

### ISSUE THREAD

**Issue by ilhyungl** [guard/guard#753]
Hi - while running bundle exec guard (using drush omega-guard), I ran into the following error:

Executing: bundle exec guard
Calling proc_open(bundle exec guard);

INFO - Guard::Compass is waiting to compile your stylesheets.
error: "hw.ncpu" is an unknown key
INFO - Guard is now watching at '/sites/all/themes/subtheme_omega'
[1] guard(main)>

I am running Omega 4 on Drupal 7. My site is hosted on Bluehost (Linux). 

Any help would be greatly appreciated. It seems this error is not that common and I have been unable to find help anywhere else. 

Thanks in advance. 

===============

Also ran it w/ -d and got the following:

12:23:49 - DEBUG - Command execution: hash stty
12:23:49 - DEBUG - Guard starts all plugins
12:23:49 - DEBUG - Hook :start_begin executed for Guard::Compass
12:23:49 - INFO - Guard::Compass is waiting to compile your stylesheets.
12:23:49 - DEBUG - Hook :start_end executed for Guard::Compass
12:23:49 - DEBUG - Hook :start_begin executed for Guard::LiveReload
RuntimeError: no acceptor (port is in use or requires root privileges) at /ruby/gems/gems/eventmachine-1.0.7/lib/eventmachine.rb:526:in `start_tc   p_server'
[2015-03-16T12:23:49.939 DEBUG Guard::Ui(12511) #E19BB24975A2] Hook :start_end e   xecuted for Guard::LiveReload
error: "hw.ncpu" is an unknown key
12:23:50 - INFO - Guard is now watching at 'sites/all/themes/hqbars_omega'
12:23:50 - DEBUG - Start interactor
[1] guard(main)> exit
12:24:14 - DEBUG - Interactor was stopped or killed
12:24:14 - DEBUG - Guard stops all plugins
12:24:14 - DEBUG - Hook :stop_begin executed for Guard::Compass
12:24:14 - DEBUG - Hook :stop_end executed for Guard::Compass
12:24:14 - DEBUG - Hook :stop_begin executed for Guard::LiveReload
12:24:14 - DEBUG - Hook :stop_end executed for Guard::LiveReload
12:24:14 - INFO - Bye bye...

**Comment by e2** [comment]
I've answered this here: https://github.com/guard/guard-livereload/issues/134 - Celluloid doesn't detect the number of CPUs on the Bluehost environment.
