### ISSUE TITLE
Warnings when running inside of minimal Docker instances

### ISSUE THREAD

**Issue by envygeeks** [guard/guard#761]
```
Could not open library 'libgtk-x11-2.0': libgtk-x11-2.0: cannot open shared object file: No such file or directory.
Could not open library 'libgtk-x11-2.0.so': libgtk-x11-2.0.so: cannot open shared object file: No such file or directory.
Could not open library 'libgtk-x11-2.0.so.0': libgtk-x11-2.0.so.0: cannot open shared object file: No such file or directory.
Could not open library 'libgtk-3': libgtk-3: cannot open shared object file: No such file or directory.
Could not open library 'libgtk-3.so': libgtk-3.so: cannot open shared object file: No such file or directory.
Could not open library 'libgtk-3.so.0': libgtk-3.so.0: cannot open shared object file: No such file or directory
```

**Comment by envygeeks** [comment]
To add a note: We could easily install those libs inside of Docker but it would be preferable that whatever library is causing these problems be allowed to be disabled.

**Comment by e2** [comment]
I think you just need to disable notifications (in Guardfile, in global config file or in command line). It's likely libnotify that's pulling this.

**Comment by envygeeks** [comment]
Sorry @e2 should have mentioned that, we did do `notifications: false` in our Guard file.

**Comment by e2** [comment]
Could you provide a strace log? (`strace -f -o guard.log bundle exec guard -d`, then exit guard).

I don't think guard is loading this. If `guard -d` isn't showing any notification lib, I can't think of how anything related to Guard could be loading a gtk/x11 library.

**Comment by envygeeks** [comment]
After running guard debug I noticed that there is an inconsistency in documentation since one place said put the notification option on the `guard` inside of the DSL but another said `notification :off` is the DSL so we changed it and the error's disappeared.

**Comment by rymai** [comment]
Edit: I'm too slow!

@envygeeks It's `notification :off`, not `notifications: false`.
