### ISSUE TITLE
Inline Guard only run once

### ISSUE THREAD

**Issue by cstony0917** [guard/guard#764]
I've create a simple inline guard to run shell command , it' works, but only run once now.

here is my guradfile

```
module ::Guard
  class Phpcli < Plugin
    def run_all
    end

    def run_on_modifications(paths)
      return exec( 'php test.php' )
    end
  end
end

guard 'phpcli' do
  watch(%r{\.php})
end
```

and the result

```
➜  guard-php  guard
14:51:54 - INFO - Guard is now watching at '/Users/zack/projects/guard-php'
1432882319%                                                                                                                                                         ➜  guard-php
```

and the test.php is simple , just echo the current time

```
<?php
echo time();
?>
```

any helps? thanks!

**Comment by cstony0917** [comment]
I have the resolution , just replace exec to `` ,

reference
* <http://tech.natemurray.com/2007/03/ruby-shell-commands.html>

```
module ::Guard
  class Phpcli < Plugin
    def run_all

    end

    def run_on_modifications(paths)
      puts nil # 為了讓輸出好看一點XD
      puts `php test.php`
    end
  end
end

guard 'phpcli' do
  watch(%r{\.php})
end
```

**Comment by e2** [comment]
You want to use `system` instead of `exec`, see: http://ruby-doc.org/core-2.2.2/Kernel.html#method-i-exechttp://ruby-doc.org/core-2.2.2/Kernel.html#method-i-exec

`exec` replaces the guard process with the php process - so it makes guard exit.

What you want instead of ``puts `php test.php``` is:
```ruby
system('php test.php')
```

**Comment by cstony0917** [comment]
Thank you :+1:
