### ISSUE TITLE
Empty css

### ISSUE THREAD

**Issue by helloncanella** [guard/guard#773]
I'm entirely new with Guard. 

For unknown reasons, Guard is generating empty css, after changes of sass files.    

I'm using ruby 2.2.1p85 and I'm on a Linux (Ubuntu 14.04).

What could I do to solve this bug?

**Comment by e2** [comment]
Guard just runs other tools when file changes - so the tool you're running with Guard is failing.

There are a few things you can try, but first

1. run Guard with the '-d' option to see what's happening:

```
bundle exec guard -d
```

2. change a sass file
3. exit Guard
4. put the output in a Gist so I can take a look

Other things that might help find the cause:
- show the context of your Guardfile (so I can see what tools you're using and at what versions)
- or, you can simply create a new repository with your project, so I can try and reproduce the problem

**Comment by helloncanella** [comment]
For some other unknown reasons, the problem fixed itself. Thank you for the offered help.

**Comment by e2** [comment]
Glad to help!
