### ISSUE TITLE
Getting guard logger to show unicorn output

### ISSUE THREAD

**Issue by dankohn** [guard/guard#784]
This is probably obvious, but I'm just trying to get guard to show the same console output I get from running `rails server`: one line per http request (since I'm running `quiet-assets`. Even at `debug` level, I only get a line about UI, but I don't see the server output. What am I doing wrong? My Guardfile:
```ruby
# Spreemo Guardfile
# More info at https://github.com/guard/guard#readme

guard :bundler do
  watch('Gemfile')
end

guard :unicorn do
  watch('Gemfile.lock')
  watch(%r{^(config|lib)/.*})
end

guard :livereload do
  watch(%r{app/views/.+\.(erb|haml|slim)$})
  watch(%r{app/helpers/.+\.rb})
  watch(%r{app/activeadmin/.+\.rb})
  watch(%r{public/.+\.(css|js|html)})
  watch(%r{config/locales/.+\.yml})
  watch(%r{(app|vendor)(/assets/\w+/(.+\.(css|js|html|png|jpg))).*}) do |m|
    "/assets/#{m[3]}"
  end
end

guard :spring, bundler: true do
  watch('Gemfile.lock')
  watch(%r{^config/})
  watch(%r{^spec/(support|factories)/})
end

logger level: :debug,
       device: STDOUT,
       template: '[:severity - :time - :progname] :message'
```

**Comment by e2** [comment]
The logger options only control Guard's API methods, such as `Guard::UI.warn`, etc. So it's up to the plugin to use that api. 

Here, you're using guard-unicorn, which just runs the server process, using STDOUT, STDERR, which guard doesn't control or redirect. 

It's probably a matter of patching guard-unicorn to either log the output in the way you want to - or - filter unicorn's output to use Guard's api.

Here's the line where unicorn is run:

https://github.com/andreimaxim/guard-unicorn/blob/02aca92911/lib/guard/unicorn.rb#L48

If you need any changes in Guard to support this, let me know (or just send a PR).

**Comment by dankohn** [comment]
Thanks very much for the explanation and link.
