### ISSUE TITLE
Notifysend shows notification with height 1px?

### ISSUE THREAD

**Issue by ITler** [guard/guard#786]
Hello,

first, I'm new to all this ruby and guard stuff. I wan't to get Ubuntu 14.04LTS Unity desktop (with current patch level) notifications from guard.

Using `libnotify` to send a notification out of `irb` **is working fine**.

    require 'libnotify'
    Libnotify.show(:body => "hello", :summary => "world", :timeout => 2.5)

But when using guard, I see a notification box with height 1px (maybe 2px). So I can't read the notification text. Please have a look at my configuration.
I guess this is a newbie mistake, but I didn't find a solution. I would appreciate your help.

#### Gemfile
    gem 'guard'
    gem 'guard-shell'
    gem 'libnotify'

#### Guardfile taken from GITHUB examples

    ignore %r{^ignored/path/}, /public/
    filter /\.txt$/, /.*\.zip/

    # leads to no display when uncommented: notification :notifysend

    guard :shell do
      watch /.*/ do |m|
        n m[0] + " has changed."
      end
    end

#### RVM (a bit older)
    rvm info

    ruby-2.1.5:

      system:
        uname:       "Linux home_dev 3.16.0-46-generic #62~14.04.1-Ubuntu SMP Tue Aug 11 16:27:16 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux"
        system:      "ubuntu/14.04/x86_64"
        bash:        "/bin/bash => GNU bash, version 4.3.11(1)-release (x86_64-pc-linux-gnu)"
        zsh:         " => not installed"

      rvm:
        version:      "rvm 1.26.11 (latest) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/]"
        updated:      "1 month 18 days 2 hours 30 minutes 7 seconds ago"
        path:         "/home/itler/.rvm"

      ruby:
        interpreter:  "ruby"
        version:      "2.1.5p273"
        date:         "2014-11-13"
        platform:     "x86_64-linux"
        patchlevel:   "2014-11-13 revision 48405"
        full_version: "ruby 2.1.5p273 (2014-11-13 revision 48405) [x86_64-linux]"

      homes:
        gem:          "/home/itler/.rvm/gems/ruby-2.1.5"
        ruby:         "/home/itler/.rvm/rubies/ruby-2.1.5"

      binaries:
        ruby:         "/home/itler/.rvm/rubies/ruby-2.1.5/bin/ruby"
        irb:          "/home/itler/.rvm/rubies/ruby-2.1.5/bin/irb"
        gem:          "/home/itler/.rvm/rubies/ruby-2.1.5/bin/gem"
        rake:         "/home/itler/.rvm/gems/ruby-2.1.5/bin/rake"

      environment:
        PATH:         "/home/itler/.rvm/gems/ruby-2.1.5/bin:/home/itler/.rvm/gems/ruby-2.1.5@global/bin:/home/itler/.rvm/rubies/ruby-2.1.5/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/itler/.rvm/bin:/home/itler/.rvm/bin:/home/itler/.rvm/bin"
        GEM_HOME:     "/home/itler/.rvm/gems/ruby-2.1.5"
        GEM_PATH:     "/home/itler/.rvm/gems/ruby-2.1.5:/home/itler/.rvm/gems/ruby-2.1.5@global"
        MY_RUBY_HOME: "/home/itler/.rvm/rubies/ruby-2.1.5"
        IRBRC:        "/home/itler/.rvm/rubies/ruby-2.1.5/.irbrc"
        RUBYOPT:      ""
        gemset:       ""

**Comment by ITler** [comment]
Forget about, I've just found the typo... Damn it...

**Comment by e2** [comment]
No problem. Glad you figured it out. Let me know if any debug mode or
something would've helped find the cause faster.

**Comment by ITler** [comment]
Hmm.. maybe: `n m[0] + " has changed."` at least is a calling `n` with one parameter `m[0] + " has changed."` As one parameter seems not to be enough for `n` to work correctly (at least in my environment where libnotify fires Unity popup), 
* some kind of error message on the guard shell 
* or a default for missing parameter value
would have been helpful.

Nevertheless  I think, that the mistake I made was to basic.
