### ISSUE TITLE
"bundle exec guard" not working

### ISSUE THREAD

**Issue by TraceyK14** [guard/guard#789]
It worked all day yesterday and then today I try to run it and nothing happens.

`C:\Users\Tracey\Desktop\NextLevelRails\MovieNight>bundle exec guard`
Result:
`C:\Users\Tracey\Desktop\NextLevelRails\MovieNight>`

Windows 10
Rails 4.2.4
Ruby 2.1.5

Let me know any information you need. 
I tried running `bundle exec guard --debug` but nothing happened

Guardfile:
<pre><code>
guard :minitest do
  # with Minitest::Unit
  watch(%r{^test/(.*)\/?test_(.*)\.rb$})
  watch(%r{^lib/(.*/)?([^/]+)\.rb$})     { |m| "test/#{m[1]}test_#{m[2]}.rb" }
  watch(%r{^test/test_helper\.rb$})      { 'test' }

  # with Minitest::Spec
  # watch(%r{^spec/(.*)_spec\.rb$})
  # watch(%r{^lib/(.+)\.rb$})         { |m| "spec/#{m[1]}_spec.rb" }
  # watch(%r{^spec/spec_helper\.rb$}) { 'spec' }

  # Rails 4
  watch(%r{^app/(.+)\.rb$})                               { |m| "test/#{m[1]}_test.rb" }
  watch(%r{^app/controllers/application_controller\.rb$}) { 'test/controllers' }
  watch(%r{^app/controllers/(.+)_controller\.rb$})        { |m| "test/integration/#{m[1]}_test.rb" }
  watch(%r{^app/views/(.+)_mailer/.+})                   { |m| "test/mailers/#{m[1]}_mailer_test.rb" }
  watch(%r{^lib/(.+)\.rb$})                               { |m| "test/lib/#{m[1]}_test.rb" }
  watch(%r{^test/.+_test\.rb$})
  watch(%r{^test/test_helper\.rb$}) { 'test' }

  # Rails < 4
  # watch(%r{^app/controllers/(.*)\.rb$}) { |m| "test/functional/#{m[1]}_test.rb" }
  # watch(%r{^app/helpers/(.*)\.rb$})     { |m| "test/helpers/#{m[1]}_test.rb" }
  # watch(%r{^app/models/(.*)\.rb$})      { |m| "test/unit/#{m[1]}_test.rb" }
end</code></pre>

Gemfile:
<pre>source 'https://rubygems.org'

gem 'rails', '4.2.4'

gem 'pg'

gem 'sass-rails', '~> 5.0'

gem 'uglifier', '>= 1.3.0'

gem 'coffee-rails', '~> 4.1.0'

gem 'jquery-rails'

gem 'turbolinks'

gem 'jbuilder', '~> 2.0'

gem 'sdoc', '~> 0.4.0', group: :doc

group :development, :test do

  gem 'byebug'

  gem 'web-console', '~> 2.0'
end

group :development do

  gem 'guard', require: false
  gem 'guard-bundler', require: false
  gem 'guard-minitest', require: false
  gem 'rb-fsevent', require: false
end

group :test do

  gem 'minitest-reporters'

  gem 'shoulda'

end

gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

</pre>

**Comment by e2** [comment]
Very weird. 

Try the following:
1. `bundle show guard`
2. `bundle binstub guard`
3. `bin/guard -v`
3. `bin/guard -i -d`

**Comment by TraceyK14** [comment]
I did the first two but when I try the third and fourth I get 
`'bin' is not recognized as an internal or external command,operable program or batch file.`

**Comment by TraceyK14** [comment]
I figured it out. I added a path variable for ansicon to load and that wasn't allowing guard to run.

**Comment by e2** [comment]
Yeah, I haven't used Windows since about 2004, so I guess the last commands should be:

3. `bin\guard -v`
4. `bin\guard -i -d`

Glad you figured it out!
