### ISSUE TITLE
Issue with Celluloid within guard?

### ISSUE THREAD

**Issue by crispen-smith** [guard/guard#790]
I'm having an issue with Guard that is preventing my system from running.  This appears to be associated with a recent software update on my Mac OSX machine as I had been using sass and guard (live-reload) with no issues for months and hadn't made any changes to ruby when this first started.

I have done a complete rebuild of my ruby and reinstalled all gems and continue to get this issue:

Console output:

    Crispens-MacBook-Pro:goal crispensmith$ bundle exec guard
    I, [2015-09-15T23:05:29.159020 #37418]  INFO -- : Celluloid 0.17.1.2 is running in BACKPORTED mode. [ http://git.io/vJf3J ]
    /Users/crispensmith/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/guard-livereload-2.4.0/lib/guard/livereload/reactor.rb:48: warning: epoll is not supported on this platform
23:05:30 - INFO - LiveReload is waiting for a browser to connect.
    /Users/crispensmith/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/celluloid-0.17.1.2/lib/celluloid/calls.rb:48:in `check': wrong number of arguments (2 for 1) (ArgumentError)
	from /Users/crispensmith/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/celluloid-0.17.1.2/lib/celluloid/calls.rb:26:in `dispatch'
	from /Users/crispensmith/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/celluloid-0.17.1.2/lib/celluloid/call/sync.rb:16:in `dispatch'
	from /Users/crispensmith/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/celluloid-0.17.1.2/lib/celluloid/cell.rb:50:in `block in dispatch'
	from /Users/crispensmith/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/celluloid-0.17.1.2/lib/celluloid/cell.rb:76:in `block in task'
	from /Users/crispensmith/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/celluloid-0.17.1.2/lib/celluloid/actor.rb:339:in `block in task'
	from /Users/crispensmith/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/celluloid-0.17.1.2/lib/celluloid/task.rb:44:in `block in initialize'
	from /Users/crispensmith/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/celluloid-0.17.1.2/lib/celluloid/task/fibered.rb:14:in `block in create'
	from (celluloid):0:in `remote procedure call'
	from /Users/crispensmith/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/celluloid-0.17.1.2/lib/celluloid/call/sync.rb:45:in `value'
	from /Users/crispensmith/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/celluloid-0.17.1.2/lib/celluloid/proxy/sync.rb:38:in `method_missing'
	from /Users/crispensmith/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/listen-2.7.12/lib/listen/listener.rb:206:in `_init_actors'
	from /Users/crispensmith/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/listen-2.7.12/lib/listen/listener.rb:87:in `block in <class:Listener>'
	from /Users/crispensmith/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/celluloid-fsm-0.20.1/lib/celluloid/fsm.rb:176:in `instance_eval'
	from /Users/crispensmith/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/celluloid-fsm-0.20.1/lib/celluloid/fsm.rb:176:in `call'
	from /Users/crispensmith/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/celluloid-fsm-0.20.1/lib/celluloid/fsm.rb:129:in `transition_with_callbacks!'
	from /Users/crispensmith/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/celluloid-fsm-0.20.1/lib/celluloid/fsm.rb:97:in `transition'
	from /Users/crispensmith/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/listen-2.7.12/lib/listen/listener.rb:100:in `start'
	from /Users/crispensmith/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/guard-2.13.0/lib/guard/commander.rb:35:in `start'
	from /Users/crispensmith/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/guard-2.13.0/lib/guard/cli/environments/valid.rb:16:in `start_guard'
	from /Users/crispensmith/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/guard-2.13.0/lib/guard/cli.rb:122:in `start'
	from /Users/crispensmith/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Users/crispensmith/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/crispensmith/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /Users/crispensmith/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Users/crispensmith/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/guard-2.13.0/lib/guard/aruba_adapter.rb:32:in `execute'
	from /Users/crispensmith/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/guard-2.13.0/lib/guard/aruba_adapter.rb:19:in `execute!'
	from /Users/crispensmith/.rbenv/versions/1.9.3-p392/lib/ruby/gems/1.9.1/gems/guard-2.13.0/bin/_guard-core:11:in `<main>'
Crispens-MacBook-Pro:goal crispensmith$ bundle exec guard

Guardfile: 

      guard 'livereload' do
        watch(%r{.+.(css|js|ejs|html)})
      end

Gemfile:

      source "https://rubygems.org"

      group :development do
      gem 'listen', '~> 2.7.12'
      gem 'hitimes'
      gem 'guard'
      gem 'guardfile'
      gem 'guard-livereload'
      gem 'guard-shell'
      gem 'sass'
      gem 'guard-sass'
    end

**Comment by e2** [comment]
I'd recommend upgrading Listen to '~> 3.0', since it doesn't use Celluloid at all.

(Unless you need Listen to run in TCP mode - if you really need TCP, see: https://github.com/guard/listen/issues/258 and explain your use case if possible).

**Comment by e2** [comment]
Otherwise, try downgrading Celluloid to earlier versions until it works again.

**Comment by crispen-smith** [comment]
This seems to have solved it.  Many thanks
