### ISSUE TITLE
gem install guard gives bad response Not Found

### ISSUE THREAD

**Issue by ravikumar8** [guard/guard#792]
Getting this error on windows 10

    C:\xampp\htdocs\lesson>gem install guard
     ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
    bad response Not Found 404 (https://rubygems.global.ssl.fastly.net/quick/Marshal.4.8/pry-0.10.2-x86-mingw32.gemspec.rz)

Followed this [Manual solution to SSL issue](https://gist.github.com/luislavena/f064211759ee0f806c88)

Still no help.

Accessed this url 
    https://rubygems.global.ssl.fastly.net/quick/Marshal.4.8/pry-0.10.2-x86-mingw32.gemspec.rz
to check its existence
gives me this 

![screenshot](https://cloud.githubusercontent.com/assets/334000/10237204/2981807c-68cc-11e5-9e55-3897c1fe1c4f.png)

**Comment by e2** [comment]
Looks like a rubygems issue. Try 'gem install pry' first.

Or, try downloading the Pry gem from here: `https://rubygems.org/downloads/pry-0.10.2-x64-mingw32.gem`

And then install it manually with: `gem install pry-0.10.2-x64-mingw32.gem`

And then try to install guard...
