### ISSUE TITLE
Tmux notifications: highlighting isn't reset on exit

### ISSUE THREAD

**Issue by dgmstuart** [guard/guard#795]
When running in tmux, and I make an error happen the status line is highlighted, but when I exit guard this highlighting isn't reset.

There's nothing explicitly mentioned in the [docs](https://github.com/guard/guard/wiki/System-notifications#tmux), but from reading #539 it sounds like the expected behaviour when exiting guard is that any tmux notifications will be reset. 

ruby-2.2.2
Rails 3.2.22
Guard 2.13.0
guard-rspec 4.6.4
OSX 10.10.5 
Tmux 2.0

The specific error I'm triggering is when guard depends on zeus and zeus isn't running:
```
» bundle exec guard --debug
14:05:02 - DEBUG - Notiffany: gntp not available (Please add "gem 'ruby_gntp'" to your Gemfile and run your app with "bundle exec".).
14:05:02 - DEBUG - Notiffany: growl not available (Please add "gem 'growl'" to your Gemfile and run your app with "bundle exec".).
14:05:02 - DEBUG - Notiffany: terminal_notifier not available (Please add "gem 'terminal-notifier-guard'" to your Gemfile and run your app with "bundle exec".).
14:05:02 - DEBUG - Notiffany: libnotify not available (Unsupported platform "darwin14.4.0").
14:05:02 - DEBUG - Notiffany: notifysend not available (Unsupported platform "darwin14.4.0").
14:05:02 - DEBUG - Notiffany: notifu not available (Unsupported platform "darwin14.4.0").
14:05:02 - DEBUG - Command execution: {"ALTERNATE_EDITOR"=>"false"} emacsclient --eval '1'
14:05:02 - DEBUG - Notiffany: emacs not available (Emacs client failed).
14:05:02 - DEBUG - Command execution: tmux -V
14:05:02 - DEBUG - Notiffany: file not available (No :path option given).
14:05:02 - DEBUG - Command execution: tmux -V
14:05:02 - DEBUG - Notiffany is using Tmux to send notifications.
14:05:02 - DEBUG - Command execution: tmux list-clients -F '#{client_tty}'
14:05:02 - DEBUG - Command execution: tmux show -t /dev/ttys001
14:05:02 - DEBUG - Notiffany is using TerminalTitle to send notifications.
14:05:03 - DEBUG - Command execution: hash stty
14:05:03 - DEBUG - Guard starts all plugins
14:05:03 - DEBUG - Hook :start_begin executed for Guard::RSpec
14:05:03 - INFO - Guard::RSpec is running
14:05:03 - DEBUG - Hook :start_end executed for Guard::RSpec
14:05:03 - INFO - Guard is now watching at '/Users/dxwduncan/dev/Personal/swingoutlondon'
14:05:03 - DEBUG - Start interactor
14:05:03 - DEBUG - Command execution: stty -g 2>/dev/null
[1] guard(main)> 
14:05:04 - DEBUG - Interactor was stopped or killed
14:05:04 - DEBUG - Command execution: stty  2>/dev/null
14:05:04 - INFO - Run all
14:05:04 - DEBUG - Hook :run_all_begin executed for Guard::RSpec
14:05:04 - INFO - Running all specs
Can't connect to master. Run zeus start first.
14:05:04 - ERROR - Failed: "zeus rspec spec -f Fuubar -r /usr/local/var/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/guard-rspec-4.6.4/lib/guard/rspec_formatter.rb -f Guard::RSpecFormatter --failure-exit-code 2  spec" (exit code: 1)
14:05:04 - DEBUG - Command execution: tmux set -q status-left-bg red

14:05:04 - DEBUG - Start interactor
14:05:04 - DEBUG - Command execution: stty -g 2>/dev/null
[1] guard(main)> exit
14:05:06 - DEBUG - Interactor was stopped or killed
14:05:06 - DEBUG - Command execution: stty  2>/dev/null
14:05:06 - DEBUG - Guard stops all plugins
14:05:06 - DEBUG - Command execution: tmux set -q -u -t /dev/ttys001 status-left-bg
14:05:06 - DEBUG - Command execution: tmux set -q -u -t /dev/ttys001 status-right-bg
14:05:06 - DEBUG - Command execution: tmux set -q -u -t /dev/ttys001 status-left-fg
14:05:06 - DEBUG - Command execution: tmux set -q -u -t /dev/ttys001 status-right-fg
14:05:06 - DEBUG - Command execution: tmux set -q -u -t /dev/ttys001 message-bg
14:05:06 - DEBUG - Command execution: tmux set -q -u -t /dev/ttys001 message-fg
14:05:06 - DEBUG - Command execution: tmux set -q -u -t /dev/ttys001 display-time
```

Guardfile: 

``` ruby
guard 'rspec', cmd: 'zeus rspec spec' do
  watch(%r{^spec/.+_spec\.rb$})
  watch(%r{^lib/(.+)\.rb$})     { |m| "spec/lib/#{m[1]}_spec.rb" }
  watch('spec/spec_helper.rb')  { "spec" }

  # Rails example
  watch(%r{^app/(.+)\.rb$})                           { |m| "spec/#{m[1]}_spec.rb" }
  watch(%r{^app/(.*)(\.erb|\.haml)$})                 { |m| "spec/#{m[1]}#{m[2]}_spec.rb" }
  watch(%r{^app/controllers/(.+)_(controller)\.rb$})  { |m| ["spec/routing/#{m[1]}_routing_spec.rb", "spec/#{m[2]}s/#{m[1]}_#{m[2]}_spec.rb", "spec/acceptance/#{m[1]}_spec.rb"] }
  watch(%r{^spec/support/(.+)\.rb$})                  { "spec" }
  watch('spec/factories.rb')                          { "spec/models" }
  watch('config/routes.rb')                           { "spec/routing" }
  watch('app/controllers/application_controller.rb')  { "spec/controllers" }
  # Capybara request specs
  watch(%r{^app/views/(.+)/.*\.(erb|haml)$})          { |m| "spec/requests/#{m[1]}_spec.rb" }

  watch('lib/out_of_date_calculator.rb') { "spec/models/event_date_functions_spec.rb" }
end
```

**Comment by dgmstuart** [comment]
Oops - submitted prematurely: I'll complete the descriptions and add my guardfile etc.

**Comment by dgmstuart** [comment]
Added the other info now

**Comment by e2** [comment]
> 15:55:59 - DEBUG - Command execution: tmux set -q window-status-current-bg red

Is that the issue? I don't know where that line came from - Guard intercepts all system() calls everywhere, so you may want to print the backtrace here:

https://github.com/guard/guard/blob/master/lib/guard/internals/debugging.rb#L47

Right now, TMux notification is in a separate project here: 

https://github.com/guard/notiffany/blob/master/lib/notiffany/notifier/tmux.rb

(The code there basically cleans up what it sets - and nothing else).

**Comment by dgmstuart** [comment]
Arg - sorry, that was in a .guard.rb file: I removed that and checked that the issue still happens, but didn't update my debug output. Will check that notify any project and update the issue with the correct output

**Comment by dgmstuart** [comment]
@e2 I've updated the output now. Should I be raising this on the notifanny project instead?

I'm guessing `tmux set -q -u -t /dev/ttys000 status-left-bg` is the command which is supposed to reset the colour? 

It doesn't seem to do anything for me. I've tried running this directly in the tmux console, but still nothing changes: 

    :set -q -u -t /dev/ttys000 status-left-bg
    :set -u status-left-bg 

The docs say:
> The -u flag unsets an option, so a session inherits the option from the global options

...and when I look at the global options (`:show -g`) I see

    status-left-style bg=red

...whereas before guard does it's thing it's like this:

    status-left-style default

So unless I've misunderstood, guard is somehow setting the option globally, when it's expecting not to (?). But that's odd, because the debug output doesn't say it's being set globally:

    22:33:23 - DEBUG - Command execution: tmux set -q status-left-bg red

The other possibility is that `/dev/ttys000` doesn't actually identify the current session. If I do `:show -t /dev/ttys000` I don't get any output. To be honest I don't really understand what `/dev/ttys000` means, so this is all just a wild guess

Then again, `:show /dev/ttys001` etc. gives a "Session not found" message

**Comment by dgmstuart** [comment]
As an experiment, I tried setting `status-left-bg` to yellow, in my `.tmux.conf` and also with an empty `.tmux.conf` and setting it globally through the terminal before running guard, but I didn't see any different results.

**Comment by e2** [comment]
> @e2 Should I be raising this on the notifanny project instead?

Doesn't matter at this point - I maintain both projects anyway.

> I'm guessing tmux set -q -u -t /dev/ttys000 status-left-bg is the command which is supposed to reset the colour?

Yes, it's supposed to "remove" the option from the ones set on that TMux session (once removed, it's set to 'default'). Without the `-q` it should show you if the option was set (and says 'unset ...') or not (shows an error).

The TMux plugin on startup only remembers a limited set of TMux options (the ones it's supposed to change only itself) here:

https://github.com/guard/notiffany/blob/master/lib/notiffany/notifier/tmux.rb#L144

It uses this to read the current options, saving them (and restoring on exit):  `tmux show -t /dev/ttys000`

> Then again, :show /dev/ttys001 etc. gives a "Session not found" message

`tmux list-clients` should show you the available clients.

Anyway, if you work out what command is causing the change - and which command would undo it, let me know and I'll work out how to add those to Notiffany.

(I'm not a TMux expert)

**Comment by dgmstuart** [comment]
:( I thought I'd updated the output but looks like it didn't work

**Comment by dgmstuart** [comment]
OK updated properly now. 

Situation is: 
  1. `tmux show -t /dev/ttys001` returns nothing
  * `tmux set -q status-left-bg red` is getting called to turn the left-hand status line red
  * `tmux set -q -u -t /dev/ttys001 status-left-bg` is supposed to be re-setting that colour (but isn't)

Maybe 1. is just a tmux bug, and that's what's stopping everything else from working? Or maybe it's a bug in my system configuration of Tmux.

**Comment by e2** [comment]
There are global options and session options - by setting a session object, the global setting is overloaded.

```
➜  ~  tmux show -g status-left-bg
status-left-bg default
➜  ~  tmux show status-left-bg
➜  ~  tmux set status-left-bg red
set option: status-left-bg -> red
➜  ~  tmux show status-left-bg
status-left-bg red
➜  ~  tmux show -g status-left-bg
status-left-bg default
➜  ~  tmux set -u status-left-bg
unset option: status-left-bg
➜  ~  tmux show -g status-left-bg
status-left-bg default
➜  ~  tmux show status-left-bg
➜  ~  
```


> tmux set -q status-left-bg red

Perhaps this command should also use the target-session (-t /dev/ttys001)?

Example:

```
tmux show -t /dev/ttys001 # nothing
tmux set status-left-bg red # sets bg for current session
tmux set status-left foobar # sets status text (redraw)
tmux show -t /dev/ttys001 # shows the changed status-left-bg and text
tmux set -u -t /dev/ttys001 status-left-bg # should reset the background color
tmux set status-left bar # sets status text again (redraw)
tmux show -t /dev/ttys001 # should show only the status text and changed
```

**Comment by dgmstuart** [comment]
Here's how that goes down on my machine, with default configs (or at least no `.tmux.conf` and no `.guard.rb`. ):

With the first form, the status only gets set globally:
``` tmux
➜  ~  tmux show -g status-left-bg
status-left-style default
➜  ~  tmux show status-left-bg
➜  ~  tmux set status-left-bg red
➜  ~  tmux show status-left-bg
➜  ~  tmux show -g status-left-bg
status-left-style bg=red
➜  ~  tmux set -u status-left-bg
➜  ~  tmux show -g status-left-bg
status-left-style bg=red
➜  ~  tmux show status-left-bg
```

With the second form, the text gets set and reset, but the background doesn't:
``` tmux
➜  ~  tmux show -t /dev/ttys001
➜  ~  tmux set  -t /dev/ttys001 status-left-bg red
➜  ~  tmux set  -t /dev/ttys001 status-left foobar
➜  ~  tmux show -t /dev/ttys001
status-left "foobar"
➜  ~  tmux set -u -t /dev/ttys001 status-left-bg
➜  ~  tmux set  -t /dev/ttys001 status-left bar
➜  ~  tmux show -t /dev/ttys001
status-left "bar"
```

This is definitely feeling like a tmux problem... 

My googling hasn't found anything though (e.g. "tmux background colour set globally")

**Comment by e2** [comment]
The following should reset the global setting (in case you changed it):

```
tmux show -g status-left-bg default
```

There's also `status-left-style` which can contain background and foreground color.

**Comment by dgmstuart** [comment]
I think I've worked it out!!!!

Looks like `status-left-bg` is no longer the expected way to do this in Tmux 2.0 (as in: it's not in the docs anymore).

Instead the approach should be `tmux set status-style "bg=red"`, which unfortunately doesn't look like it's supported by older versions.

With that, everything seems to work as expected :)

Here's the commit which added `-style: https://github.com/tmux/tmux/commit/945339b443affdaaca260605e15b5a3b9a3c6e16
It says it's backwards compatible, but clearly there are issues!

Are you able to detect a tmux version and act accordingly?

**Comment by dgmstuart** [comment]
Update: on master it _is_ backwards compatible, but there doesn't seem to be a stable release containing this fix yet: https://github.com/tmux/tmux/issues/141#issuecomment-147957256

In any case, `status-left-bg` will eventually be deprecated (as hinted by https://github.com/tmux/tmux/commit/945339b443affdaaca260605e15b5a3b9a3c6e16).

**Comment by e2** [comment]
The Notiffany TMux notifier isn't too "clever" about TMux internals, so the following may work:

```ruby

notification(:tmux, {
  success: 'bg=green',
  failure: 'bg=red',
  pending: 'bg=yellow',
  color_location: "status-style"
}) if ENV['TMUX']

```

(For the record - I'm using TMux 1.9)

**Comment by dgmstuart** [comment]
Tmux 2.1 has now been released which most likely fixes this. I'll close for now - I guess you don't need to worry about it until `status-left-bg` actually gets deprecated.

Many thanks for looking into this.

**Comment by e2** [comment]
Thanks. It's probably just a matter of setting defaults.

It might be useful to detect this bug though and warn people about it (TMux 2.0 and whatever bug there is).

I'm sure adding a warning is less work than having people work this out on their own every time. (Though, I don't know the exact scope and details of the bug).

TMux could use a Ruby client - the last time I checked, there wasn't anything good enough.
