### ISSUE TITLE
Using Guard to monitor a directory and save one file on change

### ISSUE THREAD

**Issue by tommybstitch** [guard/guard#799]
I am using Guard to essentially replicate the Rails asset pipeline for a non-Rails app. The only drawback I have encountered so far is that I have to save my `application.js.coffee` file every time I make a change to any JS file in the asset paths, in order to get the `guard-sprockets` plugin to compile the changes to my `application.js` file. 

Is there a plugin I can use to monitor my entire assets directory and when anything changes, save my `application.js.coffee` file so that it compiles? Thanks!

**Comment by e2** [comment]
I'm not sure about guard-sprockets, but something like this should work:

```ruby
guard :sprockets do
  # whenever something changes in assets, fool Guard into thinking the application.js was modified
  watch(%r{^app/assets/javascripts/}) { 'app/assets/javascripts/application.js' }
end
```

Or if not, you can just touch the file (which may cause side-effects though):

I went through the list here: https://github.com/guard/guard/wiki/Guard-Plugins and I found this: https://github.com/magplus/guard-kjell

So for a quick hack:

```ruby
guard 'kjell', cmd: "touch app/assets/application.js.coffee", :all_on_start => true do
  watch(%r{^app/assets/javascripts/})
end
```

For a pure-Ruby approach (faster), you can use https://github.com/guard/guard-yield (created by yours truly):

```ruby
  toucher = proc { FileUtils.touch('app/assets/javascripts/application.js.coffee/')  }
  guard :yield, run_on_modifications: toucher do
    watch(%r{^app/assets/javascripts/})
  end
```

There's also `guard-shell` but it has a very misleading approach to it (see https://github.com/guard/guard-yield#faq for explanations why).

And there's a feature planned for Guard 3.x where you can just manually set "dependencies" between files.

 https://github.com/guard/guard/issues/591

If the first approach (guard-sprockets) doesn't work, you can probably file an issue there - ideally with a small example repo with the problem (which helps a lot!).

**Comment by tommybstitch** [comment]
I just went with your guard-yield plugin, it seems to work really well and is very fast! Thanks.

The first approach didn't work so I will follow up with that plugin but for now, your third solution is working great. Thanks again :)
