### ISSUE TITLE
Broken link to the wiki for the page Guard Plugins

### ISSUE THREAD

**Issue by dmarcoux** [guard/guard#803]
The page about Guard Plugins isn't there anymore. It isn't accessible from the wiki's sidebar and also from the README. I guess it has been deleted. It used to be this link: https://github.com/guard/guard/wiki/Guard-Plugins

**Comment by e2** [comment]
Thanks for letting me know! 

I just restored it.

(Seems like it was accidentally deleted by the user @memopower ... )

**Comment by dmarcoux** [comment]
No worries.
