### ISSUE TITLE
Enable TravisCI on guard-annotate

### ISSUE THREAD

**Issue by cpjolicoeur** [guard/guard#805]
Hello @guard/core-team, I currently am the maintainer of the guard-annotate repository.

Can we please enable TravisCI build support on this repository?  I am not an admin, and unable to turn it on. 

Also, can we turn on Issues for this repository please.

Thanks in advance.

**Comment by e2** [comment]
Enabled and activated. Issues also. I also promoted you to "team maintainer" (GitHub changed the access model) and you should have rep admin access. Let me know if you need anything else.
