### ISSUE TITLE
reload guard with signal?

### ISSUE THREAD

**Issue by niksfirefly** [guard/guard#807]
Is there a way to reload guard with keyboard shortcut ??
I read that sending SIGTSTP is deprecated but is there another 
solution ? (i mean without using r shortcut from console)

**Comment by e2** [comment]
Just modify/touch the Guardfile. Why do you want to reload guard? (I'm
curious about the use case, because there are different answers).

**Comment by niksfirefly** [comment]
ohh silly me :)
i completely forgot about touching Guardfile
thx works like a charm

sometimes i want to restart multiple guards at once
