### ISSUE TITLE
Doesn't seem to work on OSX 10.7.5

### ISSUE THREAD

**Issue by georgeu2000** [guard/guard#813]
When a file is saved, nothing happens on a machine with OSX 10.7.5.

I have the following gems installed:

```
guard (2.12.0)
guard-compat (1.2.1)
guard-process (1.2.1)
guard-rspec (4.6.4)
rb-fsevent (0.9.6)
```

The same code works on OSX 10.9.5.

Another project has these gems and works as expected:

```
guard (2.8.2)
guard-process (1.0.6)
guard-rspec (4.3.1)
rb-fsevent (0.9.4)
```

I was able to track the issue down to rb-fsevent. Reverting to 0.9.4 fixes the issue.

There is some note of this on the rb-fsevent page: https://github.com/thibaudgg/rb-fsevent . Perhaps there should be a short note on the guard page?

**Comment by e2** [comment]
Sorry, I don't use OSX, only Linux.

Might be related to this: http://feedback.livereload.com/knowledgebase/articles/86239

**Comment by e2** [comment]
What version of `Listen` are you using?

**Comment by georgeu2000** [comment]
`listen (2.10.1)`

**Comment by e2** [comment]
I'd switch to Listen 3.x (3.0.5) first, and check again - just in case.

Also, paste some output with the `LISTEN_GEM_DEBUGGING=2` environment variable, as described here: https://github.com/guard/listen/wiki/Troubleshooting#adapter-specific-diagnostics

**Comment by e2** [comment]
Likely fixed here: https://github.com/guard/listen/issues/369

Let me knwo if not.
