### ISSUE TITLE
Pause behaviour is unexpected

### ISSUE THREAD

**Issue by Odaeus** [guard/guard#816]
I'd like to pause guard while switching branches, to me, "pause" means to stop listening for changes but when I activate pause I get:

```
[1] guard(main)> p
18:12:26 - INFO - File modification listening is now TRUE
```

Which I would expect to say "FALSE".

And when I un-pause it subsequently runs all the tests against flies that changed. I'd expect nothing to happen when I un-pause except that it goes back to "normal listening" mode.

Am I misunderstanding something? :smile:

**Comment by e2** [comment]
Thanks, I just created a PR for this.

Difference between 'pause' and 'stop': 'pause' means "stop reacting to events" and 'stop' would mean 'stop listening for events'.

'Stopping' doesn't really make sense AFAIK. It's better to just exit guard if you do want to stop for some reason.

**Comment by Odaeus** [comment]
Amazing, thank you!

Would you accept a PR for "stop" behaviour? The reason I'm keen on it is because I'd like to stop Guard during operations such as rebasing but the start-up time for Guard is not inconsequential:

```
$ date && bundle exec guard
Fri Jan 29 23:56:38 UTC 2016
23:56:41 - INFO - Guard::RSpec is running
23:56:47 - INFO - Guard is now watching at '/home/example/app'
```

So Guard is ready about 9 seconds after initiating, whereas with stop/resume it would be instant.

**Comment by e2** [comment]
First, check out `Listen`'s startup time - check the `LISTEN_GEM_DEBUGGING=1` environment variable. If you're watching too many folders on a slow drive, you might have a long Guard startup time.

I think implementing `stop` would be a bit tricky. Also, you lose the benefit of having the `Guardfile` reloaded.

A better option is probably Guard [scope/groups](https://github.com/guard/guard/wiki/Interacting-with-Guard) - by limiting the scope to only e.g. the `Guardfile` (in a `default` group), that will prevent events from being handled.
