### ISSUE TITLE
Automatic notifications with rspec, guard-shell, and libnotify

### ISSUE THREAD

**Issue by jasonl99** [guard/guard#820]
I can't seem to get notifications to work automatically.    I'm just working in plain ruby.

In Gemfile

```ruby
  gem 'rspec'
  gem 'guard-rspec'
  gem 'guard-shell'
  gem 'rb-fsevent'
  gem 'libnotify'
```

In Guardfile

```ruby
notification :libnotify

guard :shell do
   # watch(%r{^*\.rb}) { `bundle exec rspec spec/` }
   watch(%r{^*\.rb}) { `bundle exec rspec` }
end

guard :rspec, cmd: "bundle exec rspec" do
  require "guard/rspec/dsl"
  dsl = Guard::RSpec::Dsl.new(self)

  # Feel free to open issues for suggestions and improvements

  # RSpec files
  rspec = dsl.rspec
  watch(rspec.spec_helper) { rspec.spec_dir }
  watch(rspec.spec_support) { rspec.spec_dir }
  watch(rspec.spec_files)

  # Ruby files
  ruby = dsl.ruby
  dsl.watch_spec_files_for(ruby.lib_files)

end
```

When I run bundle exec guard, I can see the tests being rerun when I modify a ruby file, exactly as expected.  But I receive no notifications.

In the guard console I can do this:

```ruby
Guard::Notifier.notify('This is a test') 
# => [#<Notiffany::Notifier::Libnotify:0x000000030afef8
#  @images_path=#<Pathname:/home/jason/.rvm/gems/ruby-2.3.0/gems/notiffany-0.0.8/images>,
#  @options={:title=>"Notiffany", :transient=>false, :append=>true, :timeout=>3}>]

```
and I get a linux notification with that text preceded with a bold "Notiffany".  

At this point, I'm lost.

**Comment by e2** [comment]
Run guard with the debug option and paste the output. (`bundle exec guard -d`).

The notifiers are initialized at the beginning - it should help nail what issue you're having.

Also, check your `~/.guard.rb` file. Could be something there.

**Comment by e2** [comment]
You can also try to create a new project in a different folder - just to help locate if it's project-specific, or something more general.

**Comment by jasonl99** [comment]
Here's the debug output from starting (bundle exec guard -d) and one file save to trigger a test run.

This isn't really a project in the sense that there's any structure to it -- it's a Gemfile and a couple of ruby files with modules and classes.  I am toying around with some ideas in Pry.

I checked, and I have no ~/.guard.rb file.

I am using pry as my default REPL.  Could that be it?

```
14:15:24 - DEBUG - Notiffany is using Libnotify to send notifications.
14:15:25 - DEBUG - Command execution: hash stty
14:15:25 - DEBUG - Guard starts all plugins
14:15:25 - DEBUG - Hook :start_begin executed for Guard::RSpec
14:15:25 - INFO - Guard::RSpec is running
14:15:25 - DEBUG - Hook :start_end executed for Guard::RSpec
14:15:25 - DEBUG - Hook :start_begin executed for Guard::Shell
14:15:25 - DEBUG - Hook :start_end executed for Guard::Shell
14:15:25 - INFO - Guard is now watching at '/home/jason/things'
14:15:25 - DEBUG - Start interactor

Frame number: 0/0
14:15:33 - DEBUG - Interactor was stopped or killed
14:15:34 - DEBUG - Hook :run_on_modifications_begin executed for Guard::Shell
..........

Finished in 0.00997 seconds (files took 0.06227 seconds to load)
10 examples, 0 failures

14:15:34 - DEBUG - Hook :run_on_modifications_end executed for Guard::Shell
14:15:34 - DEBUG - Start interactor
```

**Comment by e2** [comment]
Pry shouldn't matter. You can disable interactive mode with `guard -i` to check.

This probably would take some poking around.

You can probably add some statement here:

https://github.com/guard/guard/blob/v2.13.0/lib/guard/notifier.rb#L34

like `STDERR.puts "notification called with: #{[message,options].inspect}"`

I want to know which side the problem is at: is it guard not having this method called ... or is Notiffany failing for some reason. (Notiffany is the notification library).

If you can wrap the project up in a repo or zip, I can take a look. But I might not find anything if it's not related to the project.

**Comment by e2** [comment]
I didn't notice you're using `Guard::Shell` ... it's a bit wacky the way it was implemented, so you have to be very careful. 

And you need to run notifications manually, like so:

```ruby
guard :shell do
  watch /(.*)/ do |m|
    n m[0], 'Changed'
    `say -v cello #{m[0]}`
  end
end
```

**Comment by jasonl99** [comment]
Thank you ... I have been struggling trying to figure out which pieces I need and how to tie them together.  I have figured it out and now have it working.

I removed Guard::Shell, as that wasn't really necessary (and I'm not sure why I thought it was, but probably just trying another piece of getting it to work).   

I created a "lib" directory and moved my rb files into it, since the guard :rspec block is looking for anyway, and success!  It works!   I guess the only thing that was keeping it from working right off the bat is that Guard doesn't look for ruby files in the root directory of a "project" -- and since this was just a few files, I hadn't yet bothered to create any structure.

Thanks again for your help!!

**Comment by e2** [comment]
> Guard doesn't look for ruby files in the root directory of a "project"

That's likely because of RSpec default configuration. Guard gets the config from RSpec directly.

Also, Guard doesn't watch RSpec files anyway.

Instead of Guard::Shell, you could look at Guard::Yield - it lets you cleanly use Ruby code when events happen. (Normally watch blocks are for returning files to process, not for running commands).

**Comment by jasonl99** [comment]
Thanks for the idea with Guard::Yield...I will definitely look at it.  I probably am doing myself any favors without having a bit more structure to the code I'm working on.
