### ISSUE TITLE
guard executaion fails with "stream closed" in rb-notifier ruby-2.4.0dev

### ISSUE THREAD

**Issue by nartes** [guard/guard#833]
I am starting guard and it quiting with an error `stream closed`.

This error denotes to /home/nartes/.rvm/gems/ruby-head/gems/rb-inotify-0.9.7/lib/rb-inotify/notifier.rb:300:in `readpartial'

I where using listen 3.1.3, then discovered that it fails with testes on Travis.
So after i rolledback it to listen 3.1.2, but nothing has changed.

I am using Archlinux and fs.inotify is the following:
% sysctl fs.inotify
fs.inotify.max_queued_events = 16384
fs.inotify.max_user_instances = 128
fs.inotify.max_user_watches = 524288

guard --debug > https://gist.github.com/71b804caa0c96aa65c01ea579d1ff19f
cat Gemfile > https://gist.github.com/aa4c7152f08a47346763762ad1b66486

**UPD:**
% ruby -v
ruby 2.4.0dev (2016-03-30 trunk 54439) [x86_64-linux]

**Comment by nartes** [comment]
It was my fault. I was using guard-test for rails 4.2.6. And guard-minitest solves the issue.

duplication of the issue https://github.com/guard/guard-test/issues/54

**Comment by e2** [comment]
No problem. Glad you solved it.

@nartes - still, I'm glad you posted it because of the error:

```
E, [2016-05-05T21:55:12.804376 #28533] ERROR -- : run() in thread failed: stream closed:\n 
/home/nartes/.rvm/gems/ruby-head/gems/rb-inotify-0.9.7/lib/rb-inotify/notifier.rb:300:in `readpartial'
/home/nartes/.rvm/gems/ruby-head/gems/rb-inotify-0.9.7/lib/rb-inotify/notifier.rb:300:in `readpartial'
/home/nartes/.rvm/gems/ruby-head/gems/rb-inotify-0.9.7/lib/rb-inotify/notifier.rb:271:in `read_events'
/home/nartes/.rvm/gems/ruby-head/gems/rb-inotify-0.9.7/lib/rb-inotify/notifier.rb:238:in `process'
/home/nartes/.rvm/gems/ruby-head/gems/rb-inotify-0.9.7/lib/rb-inotify/notifier.rb:221:in `run'
/home/nartes/.rvm/gems/ruby-head/gems/listen-3.1.2/lib/listen/adapter/linux.rb:38:in `_run'
/home/nartes/.rvm/gems/ruby-head/gems/listen-3.1.2/lib/listen/adapter/base.rb:78:in `block in start'
/home/nartes/.rvm/gems/ruby-head/gems/listen-3.1.2/lib/listen/internals/thread_pool.rb:6:in `block in add'\n\ncalled from:\n 
/home/nartes/.rvm/rubies/ruby-head/lib/ruby/2.4.0/forwardable.rb:192:in `start'
/home/nartes/.rvm/gems/ruby-head/gems/listen-3.1.2/lib/listen/listener.rb:68:in `block in <class:Listener>'
/home/nartes/.rvm/gems/ruby-head/gems/listen-3.1.2/lib/listen/fsm.rb:121:in `instance_eval'
/home/nartes/.rvm/gems/ruby-head/gems/listen-3.1.2/lib/listen/fsm.rb:121:in `call'
/home/nartes/.rvm/gems/ruby-head/gems/listen-3.1.2/lib/listen/fsm.rb:91:in `transition_with_callbacks!'
/home/nartes/.rvm/gems/ruby-head/gems/listen-3.1.2/lib/listen/fsm.rb:57:in `transition'
```

Is there any chance you can create a simple example so I can reproduce this error myself?

**Comment by nartes** [comment]
https://gist.github.com/456d52070f3bcea1fdb055ab5aa46d33

**Comment by e2** [comment]
I can't seem to reproduce it.

Can you try it with this branch:

```ruby
gem 'rb-inotify', github: 'e2/rb-inotify`, branch: 'misc_bugfixes'
```

?

**Comment by nartes** [comment]
https://gist.github.com/anonymous/f497146642a2c003f78d2e8c15a36e4e

**Comment by e2** [comment]
What if you run `bundle exec guard` instead?

If you run `guard` without bundler, it won't load gems from git sources. If it did, the rb-inotify location would be:

```
/home/nartes/.rvm/gems/ruby-head/gems/ruby-head/bundler/gems/rb-inotify-be4cf88b4dab
```

**Comment by nartes** [comment]
yep, bundle exec guard --debug works fine
So your rb-notify version solves the issue

**Comment by e2** [comment]
Great. I'll leave it up for now. You can build your own gem from it.

I think I'll add a few more patches and I'l release my own gem with it. If the maintainer for the rb-inotify projects picks up the changes, we can always switch back to the original version.

Thanks for setting this up!

**Comment by nartes** [comment]
You are welcome! Nice to see solved issue)

**Comment by ioquatix** [comment]
I'm having this issue too. I don't understand what the fix here is, can someone elaborate a bit?

**Comment by nartes** [comment]
You may try to use this gem
gem 'rb-inotify', github: 'e2/rb-inotify`, branch: 'misc_bugfixes'
If it has not changed since that time.

**Comment by ioquatix** [comment]
@nartes Yeah, I see, it's still broken, I filed a(nother?) bug report.

**Comment by ioquatix** [comment]
I've merged a fix for this into rb-inotify. I'm planning to make a new release soon.
