### ISSUE TITLE
Add :svg to extensions in Guardfile

### ISSUE THREAD

**Issue by frankie-loves-jesus** [guard/guard#841]
Hi! Shouldn't `svg: :svg,` be added to `extensions` at the top of the Guardfile?

**Comment by e2** [comment]
I have not idea what you are talking about. Is this an issue for the right project?

Are you talking about notification?

**Comment by e2** [comment]
You should open this in the guard-livereload project here: https://github.com/guard/guard-livereload/issues/new

(The guard/guard project is only for managing extensions).

**Comment by e2** [comment]
P.S. I'd be glad to add SVG to the list. You can open an issue or a pull request directly.
