### ISSUE TITLE
Tmux red/green/yellow colouring - selecting foreground text colour

### ISSUE THREAD

**Issue by HaleTom** [guard/guard#843]
How can I change the foreground text colour of the red/green session name?

My Tmux session name is coloured based on the red/green status, but the name itself is very hard to read as the default red and green are quite bright, and the default text colour is a light grey. 

I've worked around it for the meantime setting darker background shades, but Ideally I'd like to set the foreground text to a different colour (eg black).

**Comment by e2** [comment]
That's handled by the Notiffany project: https://github.com/guard/notiffany.

Parameter names are dynamic, e.g.:

https://github.com/guard/notiffany/blob/322d79a/spec/lib/notiffany/notifier/tmux_spec.rb#L516

I just added the following to the Readme:

https://github.com/guard/notiffany/blob/master/README.md#customizing-options

Basically things like `fail_message_color`, `success_message_color` or even `foo_message_color` (for notifications of type `foo` if anyone ever sends one).

I'm closing this.

If you have an issue with notifications, open it in the [Notiffany](https://github.com/guard/notiffany/issues) project
