### ISSUE TITLE
Guard does not detect file changes intermitently

### ISSUE THREAD

**Issue by rhulse** [guard/guard#848]
This can happen at startup, or after running the complete test suite. I have the same issue with live reload. 

It appears that the file change is not detected, or is not passed through to Guard. On one occasion it appeared to be stuck, and then suddenly ran the tests for the last 3 files I had saved.

This is latest OSX, latest versions of the all the related Gems.

**Comment by rhulse** [comment]
Here are the Gemfile and Guardfile

[Gemfile.txt](https://github.com/guard/guard/files/398782/Gemfile.txt)
[Guardfile.txt](https://github.com/guard/guard/files/398783/Guardfile.txt)

**Comment by e2** [comment]
I think the best way to find out what's wrong is to run the following:

`LISTEN_GEM_DEBUGGING=2 bundle exec guard -d > guard.log 2>&1`

and then trying to reproduce the problem.

Then you can upload the log file as a Gist and I'll be able to see what's wrong.

Sometimes it may be the editor not saving fast enough.

You can try `bundle exec guard -y 0.3` (the higher the value, the less likely it will be stuck - you shouldn't need more than 0.5).

The debugging above will show what filesystem events you're getting, how scanning is working, etc.

If the logfile becomes huge that may also be a problem.

I'll probably be adding more debug options in a few days, so that might help.

**Comment by rhulse** [comment]
OK, I commented out livereload for this test

https://gist.github.com/rhulse/528c8a450a939f5dd8f7380b5f74b33e

I saved many different files and it did not see any changes at all. Also, when I existed (after doing a bundle update on the gems (I was a couple of point releases behind) it's now giving me a bunch of error output when I exit.

An interesting side effect (and I have noticed this before this problem) is that sometimes after exiting Guard the terminal is messed up. Typing anything comes up blank, and pressing enter returns the prompt on the same line instead of a new line.

I also tried the -y 0.3 but it made no difference.

**Comment by e2** [comment]
First, try updating your Listen and rb-fsevent versions in your `Gemfile`:

```ruby
gem 'listen', '~> 3.1.5'
```

and `bundle update listen'

or even:

```
gem 'listen', '~> 3.0.8'
```

and `bundle update listen'.


There are a few known issues as of right now - I probably won't get deeper to this until Saturday. (And those will take some time to fix).

Meanwhile, you can try:

`LISTEN_GEM_DEBUGGING=2 bundle exec guard -n f -i -d > guard.log 2>&1`

You won't have a Pry console, but at least your readline shouldn't interfere with the debugging.

**Comment by rhulse** [comment]
OK, I have been using debug mode for a week.


When I start guard I frequenrly get this output:

    D, [2016-08-13T11:55:45.936551 #42661] DEBUG -- : fsevent: watching: "/Users/rhulse/Sites/elf"
    D, [2016-08-13T11:55:45.936735 #42661] DEBUG -- : Waiting for processing to start...
    11:55:46 - INFO - Guard is now watching at '/Users/rhulse/Sites/elf'
    11:55:46 - DEBUG - Guards jobs done. Sleeping...

At which point nothing happens for about 130 seconds:

    I, [2016-08-13T11:57:56.820977 #42661]  INFO -- : Record.build(): 130.88417 seconds
    D, [2016-08-13T11:57:56.821133 #42661] DEBUG -- : fsevent: running worker: # <FSEvent:0x007fc9533981a8 @paths=["/Users/rhulse/Sites/elf"], @callback=#<Proc:0x007fc953398360@/Users/rhulse/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/listen-3.1.5/lib/listen/adapter/base.rb:41 (lambda)>, @options=["--latency", "0.1"]>

Things then usually work fine.

I have yet to capture output after guard fails after having worked for a while. Will probably have that in a few more days.

**Comment by e2** [comment]
Thanks for the update.

130 seconds is a very long amount of time!

You are probably watching more files than you need, see:

https://github.com/guard/guard/wiki/Guardfile-DSL---Configuring-Guard#directories

and the `:ignore` option too:

https://github.com/guard/guard/wiki/Guardfile-DSL---Configuring-Guard#ignore

You should make sure than files that you aren't modyfing (like node.js
installed files) are either not watched or ignored.o

On OSX you're forced to watch directories recursively, so if you use
the `:directories` option (which I highly recommend!), Guard won't
track files in the main directory (e.g. Guardfile).

The workaround is symlinks, e.g. creating a `config` directory, moving
files you want to watch there (like `Guardfile`) and symlinking, e.g.

```
$ mkdir config
$ git mv Guardfile config
$ ln -s ./config/Guardfile .
$ git add Guardfile
```

Hope that helps!

**Comment by rhulse** [comment]
Yes, that helps a great deal:

    09:20:40 - INFO - Guard is now watching at '/Users/rhulse/Sites/elf/app', '/Users/rhulse/Sites/elf/config', '/Users/rhulse/Sites/elf/lib', '/Users/rhulse/Sites/elf/spec'
    I, [2016-08-14T09:20:40.336535 #31640]  INFO -- : Record.build(): 0.01136 seconds

Startup time is great now. Can we leave this ticket open for now, and I will close it in a few days when I have confirmed that it does not randomly hang still after running for a while?

**Comment by e2** [comment]
Sure. The hangups may be a different issue.

**Comment by rymai** [comment]
Let's close for now!

**Comment by rhulse** [comment]
Yes, sorry, late to the party. OK to close.
