### ISSUE TITLE
Expose running plugin as logger progname

### ISSUE THREAD

**Issue by christhekeele** [guard/guard#849]
Currently, it looks the `progname` of a Lumberjack log message is always `Guard::UI`.

I'm not sure if this is intentional, my reading of the source code suggests that the intention is for it to be the running plugin name instead.

I've been trying to hack this behaviour into guard to little avail. I've mostly been experimenting in [these lines](https://github.com/guard/guard/blob/2ba5b1727b1c65c33ffbffd36c7d1e6874919dde/lib/guard/ui.rb#L169-L210):

```ruby

      # Filters log messages depending on either the
      # `:only`` or `:except` option.
      #
      # @param [String] plugin the calling plugin name
      # @yield When the message should be logged
      # @yieldparam [String] param the calling plugin name
      #
      def _filter(plugin)
        only = options[:only]
        except = options[:except]
        plugin ||= calling_plugin_name

        match = !(only || except)
        match ||= (only && only.match(plugin))
        match ||= (except && !except.match(plugin))
        return unless match
        yield plugin
      end

      # @private
      def _filtered_logger_message(message, method, color_name, options = {})
        message = color(message, color_name) if color_name

        _filter(options[:plugin]) do |plugin|
          reset_line if options[:reset]
          logger.send(method, message, plugin)
        end
      end

      # Tries to extract the calling Guard plugin name
      # from the call stack.
      #
      # @param [Integer] depth the stack depth
      # @return [String] the Guard plugin name
      #
      def calling_plugin_name(depth = 2)
        name = /(guard\/[a-z_]*)(\/[a-z_]*)?.rb:/i.match(caller[depth])
        return "Guard" unless name
        name[1].split("/").map do |part|
          part.split(/[^a-z0-9]/i).map(&:capitalize).join
        end.join("::")
      end
```

It'd be nice to tag, as well as filter, my guard logs.

**Comment by e2** [comment]
Yes, that could be broken.

After `def calling_plugin` add a debug statement:

```ruby
STDERR.puts caller * "\n"
```

I'm guessing the depth (2) is not far enough for `calling_plugin_name` to find the plugin name in the call stack.

**Comment by christhekeele** [comment]
No, it's something more than that–`calling_plugin_name` isn't working period for me; I modified it to use `caller.length` for the depth to no effect.

Furthermore, that'd mean that `plugin` should be set to `"Guard"`, not `"Guard::UI"`, right? `progname` is definitely coming up the latter.

**Comment by christhekeele** [comment]
Actually, modifying it to use `caller[caller.length]` did have an effect–now `plugin` is getting set to `"Guard"` consistently, but never anything else. The value of `caller` is [here](https://gist.github.com/christhekeele/183786b5d6e3bf8562cf0d2d9808954a).

**Comment by christhekeele** [comment]
Oh, of course-It's finding guard/ui in the callstack before bundler. I'll send a PR.

**Comment by christhekeele** [comment]
Actually it never searched the call stack, it only looked at that particular depth in the call stack.

Searching the call stack would look more like:

```ruby
caller.take(depth).find{|l|%r{(guard\/[a-z_]*)(/[a-z_]*)?.rb:}i.match l}
```

You could improve the regex to filter out guard itself with a negative lookbehind, something like

```ruby
caller.take(depth).find{|l|%r{(?<!guard\/lib\/)(guard\/[a-z_]*)(/[a-z_]*)?.rb:}i.match l}
```

But that would still (in my call stack) turn up `guard/compat` first. Perhaps there's a better way to do this?

**Comment by christhekeele** [comment]
I've made two pull requests: one fixes this issue by using Lumberjack's default and override tooling to determine the progname instead of relying on `calling_plugin_name`.

The second at least partially addresses some existing issues with the implementation of `calling_plugin_name` that are impacting Guard's ability to correctly consume the filter/exclude certain guards from the log. It doesn't 100% fix it but it's a start.
