### ISSUE TITLE
Executing task on guard start and/or exit?

### ISSUE THREAD

**Issue by ITler** [guard/guard#854]
Hello,

when starting or exiting guard, I'd like to fire a custom function, which is defined in my Guardfile.
How could I do this? Or even better for learing? Where should I look in the code, to be able to answer my question by myself?

Kind regards
ITler

**Comment by e2** [comment]
You can create an inline Guard plugin (see Wiki) that has a `:stop`
method - and you can do whatever you want in the stop method.

Or, you can also checkout guard-yield, which lets you run a piece of
Ruby code during a Guard action (like `:stop`).

The first option is better if you prefer to have your own "plugin" for
the action that you can reuse across projects.

The second if you just want to handle the action in your Guardfile.

**Comment by ITler** [comment]
Thank you, I'll give this a try.
