### ISSUE TITLE
Watching fixtures YML files to run model test

### ISSUE THREAD

**Issue by aldrienht** [guard/guard#855]
Since fixtures are in plural form, let say:

**Fixture**          **Model**
  users.yml  = user

I can do in **Guardfile** like, by simple adding "s":

watch(%r{^test/fixtures/(.+)s\.yml$})                   { |m| "test/models/#{m[1]}_test.rb"}

But what if in other cases like:

**Fixture**          **Model**
  abilities.yml  = ability

Is there a way to use like **pluralize** or regex ?

**Comment by e2** [comment]
Probably something like this:

```ruby
watch(%r{^test/fixtures/(.+)(?:s|ies|es).yml$}) { |m| "test/models/#{m[1]}_test.rb"}
```

Or you can create your own method, e.g.

```ruby

def plural_to_singular(plural)
  # e.g. use ActiveSupport here to convert 'abilities' to 'ability'
end

def files_for_yml(plural)
  singular = plural_to_singular(plural)
  "test/models/#{singular}_test.rb"
end

watch(%r{^test/fixtures/(.+).yml$}) { |m| files_for_yml(m[1])}
```

Or, you can do it the other way around:

```ruby
Dir['test/models/*_test.rb'].each do |test|  
  plural = pluralize(test[/\/(.+)_test.rb/, 1])
  yml_file = "test/fixtures/#{plural}.yml"
  watch(yml_file) { test }
end
```

**Comment by e2** [comment]
Could be useful as a wiki example if ActiveSupport is used.

Mostly, it would be plugin dependent though (e.g. best done by Guard::RSpec or Guard::Minitest, etc.)

**Comment by aldrienht** [comment]
Hi @e2 , i tried to used this one,
`
watch(%r{^test/fixtures/(.+)(?:s|ies|es).yml$})         { |m| "test/models/#{m[1]}_test.rb"}
`
but it seems **not working** with **ies & es** suffix.
It works in simple **/s/** form.

**Comment by e2** [comment]
That's because `cats` -> `cat`, but `abilities` -> `abilit`.

So you'll probably need something like:

```ruby
watch(%r{^test/fixtures/(.+(?:s|ies|es)).yml$}) do |m|
 "test/models/#{ActiveSupport::Inflector.singularize(m[1])}_test.rb"
end 
```

**Comment by aldrienht** [comment]
Hi Cezary,

Sorry for late response about the issue.
*YES* your code above works.

Just need to require ActiveSupport Inflector in Guardfile, require
'active_support/inflector'

Thank you very much.
