### ISSUE TITLE
guard -c doesn't clears screen properly on OS X

### ISSUE THREAD

**Issue by TG-KK** [guard/guard#858]
On OS X 10.11.6, "guard -c" doesn't clears the screen entirely on each run

It just clears current screen but not the entire scroll-back window buffer

Same behavior on Terminal(v2.6.1) as well as iTerm(v3.0.10)
Default Shell: Fish(v2.3.1)

**Comment by e2** [comment]
I don't have OSX, so I can't test.

Guard uses the `clear` command on OSX: https://github.com/guard/guard/blob/master/lib/guard/terminal.rb

I'm guessing Guard will have to use something else on OSX, see:

http://askubuntu.com/questions/25077/how-to-really-clear-the-terminal

Let me know which solution there works for you.

As a workaround, you can create a shell script, with the command you want and call it 'clear'.

E.g. if your project is `/Users/Me/myproject`, create `/Users/Me/myproject/bin/clear` with the command you want, and run Guard with the new path: `PATH=/Users/Me/myproject/bin/clear:$PATH bundle exec guard`.
