### ISSUE TITLE
lumberjack dependency causes Fixnum deprecation warning on Ruby 2.4.0

### ISSUE THREAD

**Issue by bgentry** [guard/guard#863]
> /Users/bgentry/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/lumberjack-1.0.10/lib/lumberjack/log_entry.rb:11: warning: constant ::Fixnum is deprecated

Should be resolved in https://github.com/bdurand/lumberjack/pull/28, which isn't merged yet

**Comment by bgentry** [comment]
cool, that PR is merged. Should be able to fix this deprecation warning with a new release of both gems.

**Comment by koic** [comment]
Hi @bgentry. lumberjack (1.0.11) has been released.
https://rubygems.org/gems/lumberjack/versions/1.0.11

This release version includes https://github.com/bdurand/lumberjack/pull/28.

Thanks.

**Comment by noraj1337** [comment]
I still have
```
/home/shark/.rvm/gems/ruby-2.4.0/gems/lumberjack-1.0.10/lib/lumberjack/logger.rb:203: warning: constant ::Fixnum is deprecated
```

**Comment by rymai** [comment]
@noraj1337 `guard` depends on `lumberjack` `~> 1.0` so you should be able to update it with `bundle update lumberjack`.

**Comment by noraj1337** [comment]
@rymai as you can see it was `lumberjack-1.0.10` so > 1.0

**Comment by noraj1337** [comment]
I just tested in a new env:

```
$ gem install guard
[...]
Successfully installed pry-0.11.1
Fetching: lumberjack-1.0.12.gem (100%)
[...]

$ guard # no warning

$ gem uninstall lumberjack

$ gem install lumberjack --version 1.0.11

$guard # no warning

$ gem uninstall lumberjack

$ gem install lumberjack --version 1.0.10

$ guard # Warning now !!!
```

**Comment by noraj1337** [comment]
PR fix lumberjack version runtime dependency
https://github.com/guard/guard/pull/882

**Comment by noraj1337** [comment]
@rymai seems you closed too soon  :satisfied:

**Comment by rymai** [comment]
@noraj1337 `lumberjack ~> 1.0` means that it accepts `lumberjack` from `>= 1.0 to < 2.0`, there's no need to update the dependency in the `.gemspec` to solve this problem, you can just update your `Gemfile.lock`. Or maybe you're not using Bundler, in that case you need to run `gem update lumberjack` as you've done above.

**Comment by noraj1337** [comment]
@rymai Yes I was wrong about `< 1.1`.

But `>= 1.0 to < 2.0` includes `1.0.0` to `1.0.10` (that we want to exclude).

So we need `>= 1.0.10 to < 2.0` as I understand.
