### ISSUE TITLE
I deleted Wiki Footer?

### ISSUE THREAD

**Issue by gowtham-sai** [guard/guard#875]
Accidentally I deleted Wiki Page. It this true? Do I have access to delete ?

Here is the backup.
This wiki and the Guard [README](https://github.com/guard/guard#readme) document contains a
lot of information, please take your time and read these instructions carefully.

If you run into any trouble, you may start by [understanding how Guard works](https://github.com/guard/guard/wiki/Understanding-Guard).

We provide [detailed changes for each Guard release](https://github.com/guard/guard/releases).

Be sure to read the [CONTRIBUTING](https://github.com/guard/guard/blob/master/CONTRIBUTING.md)
guidelines before reporting a new Guard issue or open a pull request.

If you have any questions about the Guard usage or want to share some information with the
Guard community, please go to one of the following places:

* [Google+ community](https://plus.google.com/u/1/communities/110022199336250745477)
* [Google group](http://groups.google.com/group/guard-dev)
* [StackOverflow](http://stackoverflow.com/questions/tagged/guard)
* IRC channel `#guard` (irc.freenode.net) for chatting

**Comment by rymai** [comment]
> Do I have access to delete ?

It appears so! :)

> Here is the backup.

Thanks for having a backup! 😌

**Comment by rymai** [comment]
Yeah, apparently, everyone has access (it's a wiki after all), but since this is backed by a Git repo, it's not a big issue:

```
* cc1ea8b - (HEAD -> master, origin/master, origin/HEAD) Destroyed _Footer (markdown) (2 days ago) <Gowtham Sai>
```

**Comment by rymai** [comment]
It looks like there is an option to restrict the editing to members with commit access only, though:

<img width="432" alt="screen shot 2017-08-07 at 10 12 41" src="https://user-images.githubusercontent.com/1168/29017870-08a2908e-7b59-11e7-977a-94a6533f357d.png">

But I don't think we need to enable it.
