### ISSUE TITLE
Why does guard specify the files to be watched?

### ISSUE THREAD

**Issue by emilebosch** [guard/guard#913]
Hi all! I tried to drop the question in IRC but no response. Why does guard requires the files to be watched specified? It seems a bit silly or am I missing something? I would say that the Guard plugin itself knows what to watch by default? Only in like 10% of the cases its probably different, so then an escape hatch/override would be handy. Now it just makes it annoying to copy paste it etc and burns braincycles.

Example:

- A gem file watcher knows that the gem file needs to be changed. So why do I need to specify it?
- A spec watchatcher knows to watch the spec directory

Hope I miss something, thanks a lot!

**Comment by rymai** [comment]
@emilebosch Hi, could you please give examples of what you find silly? Thanks in advance.

**Comment by emilebosch** [comment]
Sorry silly is not the right word. I mean not very DRY.  As i said it could be that i am missing a set of defaults. Ill send over a couple of examples, when i am behind my laptop

**Comment by emilebosch** [comment]
So as an example, the bundler guard. The default would be to watch for gemfile and gemfile.lock changes in 95% of the cases. 

If i am not mistaken i need to add the files to be watched to the guard file or run guard init.

I rather just want to add it like this

‘’’
guard :bundler
‘’’

And it just works. This is because that is 95% of the cases enough. With upgrades of the gem i also dont need to think about changing my guard file.

This is what i mean.

**Comment by emilebosch** [comment]
@rymai does this clarify things?

**Comment by rymai** [comment]
@emilebosch We chose to have the watch rules explicit in the `Guardfile`, but you don't have to type them yourself, as you discovered, you can use `guard init bundler` and the default rules will be added to your `Guardfile` automatically.

Hope that helps!

**Comment by rymai** [comment]
> I understand that, but I would think that's not very dry nor necessary, why generate code for something that's 95% of the cases the default.

If you don't have to modify it, then it doesn't hurt to have it generated, either, the advantages are that:

- the rules are explicit
- you can modify them easily

The disadvantages are that:

- if new default rules are added by a plugin, they won't be automatically used

That being said, there are discussion to improve/change that:

- https://github.com/guard/guard/issues/831
- https://github.com/guard/guard/issues/830

I'm going to close this issue in favor of these 2 issues above. Thanks again!

**Comment by rymai** [comment]
> I'm going to close this issue in favor of these 2 issues above. Thanks again!

Already closed! 👅
