### ISSUE TITLE
Alternative to `Guardfile`

### ISSUE THREAD

**Issue by svoop** [guard/guard#921]
In the light of Bundler 2 dropping `Gemfile` in favour of `gems.rb` (while still accepting `Gemfile` for most likely a long while to come):

How about adding a similar alternative to Guard, say, accept both `guard.rb` and `Guardfile`?

**Comment by rymai** [comment]
That's a good idea, thanks!

**Comment by svoop** [comment]
@rymai 

I've implemented this lil feature: https://github.com/svoop/guard/commit/4a53600c3a54693f05d35fdc6e2cfbfec8401c4e

However, I'm not sure where the default guard file tests are. There's some [setup here](https://github.com/svoop/guard/blob/master/spec/lib/guard/guardfile/evaluator_spec.rb#L12) but I don't see where it is actually being used in tests. Could you give me a hint?

(Besides: The test suite doesn't really work on my machine with Ruby 2.6.3. I've tried as usual with `bundle install; bundle exec guard`, but even if I break tests e.g. in `evaluator_spec.rb`, the suite runs without failures.)

**Comment by rymai** [comment]
> I've implemented this lil feature: svoop@4a53600

@svoop Awesome, thanks!

> However, I'm not sure where the default guard file tests are. There's some [setup here](https://github.com/svoop/guard/blob/master/spec/lib/guard/guardfile/evaluator_spec.rb#L12) but I don't see where it is actually being used in tests. Could you give me a hint?

They are not used explicitly, the variables are only eagerly created with `let!` but I agree I'm not sure these are needed.

The actual stubbing of these files is done via `stub_guardfile`, `stub_user_guardfile`, `stub_user_guard_rb`, and `stub_user_project_guardfile` in https://github.com/svoop/guard/blob/master/spec/spec_helper.rb#L42-L56.

**Comment by svoop** [comment]
@rymai Ouch, I totally forgot about this. Better late than never: PR #938
