### ISSUE TITLE
Fixing 2.6 support

### ISSUE THREAD

**Issue by ioquatix** [guard/guard#922]
I've spent some time today trying to update rb-inotify and guard/listen to support Ruby 2.6 - there is some breaking changes in the way Pathname interacts with rspec-mock and Ruby 2.6 - I've made some upstream changes to fix this, but still waiting to merge it.

https://github.com/ruby/ruby/pull/2049

**Comment by olleolleolle** [comment]
Did #928 fix this?

**Comment by rymai** [comment]
@olleolleolle I think so! 🎉
