### ISSUE TITLE
Change default global history location to be XDG compliant

### ISSUE THREAD

**Issue by quintrino** [guard/guard#950]
It would be great if guard stored history in XDG_DATA_HOME if it was set, otherwise falling back to ~/.guard_history if it wasn't. 

More about the XDG here. https://wiki.archlinux.org/index.php/XDG_Base_Directory

Alternatively, even if this wasn't achievable even just checking for a GUARD_HISTORY_LOCATION environment variable to use would also address some of the issues. 

For context I work on projects where modifying the guardfile is beyond the scope of my role or are team based with different preferences for how the guardfile should be set up and therefore setting the history location in the guardfile is not feasible.

**Comment by olleolleolle** [comment]
@quintrino Did this https://github.com/guard/guard/pull/962 fix this issue?

**Comment by rymai** [comment]
I think it did. Closing optimistically. :)

**Comment by quintrino** [comment]
Hi @olleolleolle, yes, I created #962 to solve this.
