### ISSUE TITLE
Pry::Prompt argument error when running guard

### ISSUE THREAD

**Issue by hyunwoona** [guard/guard#966]
Hi,

I've configured Guardfile and I'm trying to run guard for the first time. However, I am getting the following error.

```
eric@MacBook-Pro:~/code/$ guard

12:21:14 - INFO - Bye bye...
/Users/eric/.rvm/gems/ruby-2.4.6/gems/guard-2.16.2/lib/guard/jobs/pry_wrapper.rb:284:in `initialize': wrong number of arguments (given 3, expected 0) (ArgumentError)
	from /Users/eric/.rvm/gems/ruby-2.4.6/gems/guard-2.16.2/lib/guard/jobs/pry_wrapper.rb:284:in `new'
	from /Users/eric/.rvm/gems/ruby-2.4.6/gems/guard-2.16.2/lib/guard/jobs/pry_wrapper.rb:284:in `_configure_prompt'
	from /Users/eric/.rvm/gems/ruby-2.4.6/gems/guard-2.16.2/lib/guard/jobs/pry_wrapper.rb:151:in `_setup'
	from /Users/eric/.rvm/gems/ruby-2.4.6/gems/guard-2.16.2/lib/guard/jobs/pry_wrapper.rb:68:in `initialize'
	from /Users/eric/.rvm/gems/ruby-2.4.6/gems/guard-2.16.2/lib/guard/interactor.rb:17:in `new'
	from /Users/eric/.rvm/gems/ruby-2.4.6/gems/guard-2.16.2/lib/guard/interactor.rb:17:in `initialize'
	from /Users/eric/.rvm/gems/ruby-2.4.6/gems/guard-2.16.2/lib/guard.rb:67:in `new'
	from /Users/eric/.rvm/gems/ruby-2.4.6/gems/guard-2.16.2/lib/guard.rb:67:in `setup'
	from /Users/eric/.rvm/gems/ruby-2.4.6/gems/guard-2.16.2/lib/guard/commander.rb:32:in `start'
	from /Users/eric/.rvm/gems/ruby-2.4.6/gems/guard-2.16.2/lib/guard/cli/environments/valid.rb:16:in `start_guard'
	from /Users/eric/.rvm/gems/ruby-2.4.6/gems/guard-2.16.2/lib/guard/cli.rb:122:in `start'
	from /Users/eric/.rvm/gems/ruby-2.4.6/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
	from /Users/eric/.rvm/gems/ruby-2.4.6/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/eric/.rvm/gems/ruby-2.4.6/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
	from /Users/eric/.rvm/gems/ruby-2.4.6/gems/thor-1.0.1/lib/thor/base.rb:485:in `start'
	from /Users/eric/.rvm/gems/ruby-2.4.6/gems/guard-2.16.2/lib/guard/aruba_adapter.rb:32:in `execute'
	from /Users/eric/.rvm/gems/ruby-2.4.6/gems/guard-2.16.2/lib/guard/aruba_adapter.rb:19:in `execute!'
	from /Users/eric/.rvm/gems/ruby-2.4.6/gems/guard-2.16.2/bin/_guard-core:11:in `<main>'
```

I checked the line that's failing, and it's initializing `Pry::Prompt` with 3 arguments. I've looked at `Pry::Prompt` documentation and it takes 3 arguments.
I installed `rb-readline`, and tried `bundle exec guard`.

**Comment by hyunwoona** [comment]
When I comment out `Pry::Prompt.new("Guard", "Guard Pry prompt", prompt_procs)` part, like


```
        prompt =
          # if Pry::Prompt.is_a?(Class)
          #   Pry::Prompt.new("Guard", "Guard Pry prompt", prompt_procs)
          # else
            prompt_procs
          # end
```

guard starts

**Comment by bsmith-optoro** [comment]
I had the same problem. I was on pry 0.10, I updated to 0.13 which fixed it. Guard's pry version dependency should likely be updated.

**Comment by rymai** [comment]
@hyunwoona I'm curious what is your Pry version? The code is supposed to use the correct method depending on whether `Pry::Prompt` is a class or not (this was changed in https://github.com/pry/pry/pull/1877/files), released in Pry 0.13.0: https://github.com/pry/pry/blob/v0.13.0/lib/pry/prompt.rb.

**Comment by olleolleolle** [comment]
https://github.com/guard/guard/pull/965 made an attempt earlier.

**Comment by larouxn** [comment]
Another attempt is up here. https://github.com/guard/guard/pull/974

Trying to unblock `pry-byebug` bumps so peeps can stop seeing the following.
<img width="924" alt="Screen Shot 2021-07-14 at 09 58 47" src="https://user-images.githubusercontent.com/1557529/125545618-97822e6b-4bcf-4239-b5a8-85f3893c3716.png">

**Comment by rymai** [comment]
As explained in https://github.com/guard/guard/issues/980#issuecomment-1132711925, updating to Guard 2.18.0 should solve this.
