### ISSUE TITLE
guardgem.org is down

### ISSUE THREAD

**Issue by beporter** [guard/guard#977]
The sit is not currently loading for me. Screenshot: 
<img width="1259" alt="guardgem org-not-loading" src="https://user-images.githubusercontent.com/637270/147286433-d8e0b0a1-6f14-4b30-a9e1-e54ec3f4a29d.png">
 
The error is due to `GET | https://documentup.com/guard/guard?config={"theme":"v1","name":"Guard","travis":true,"issues":true,"twitter":["rymai","thibaudgg"]}&callback=callback
`

returning a 500, which in turn causes a JS error:

```
The resource from “https://documentup.com/guard/guard?config=%7B%22theme%22%3A%22v1%22%2C%22name%22%3A%22Guard%22%2C%22travis%22%3Atrue%2C%22issues%22%3Atrue%2C%22twitter%22%3A%5B%22rymai%22%2C%22thibaudgg%22%5D%7D&callback=callback” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).
```

**Comment by thibaudgg** [comment]
Hi @beporter, thanks for the report!

It seems like https://documentup.com is down, that's why. Let see if it's coming back online.

**Comment by briangadoury** [comment]
Currently still down. Not mentioning to be rude, just mentioning in case it's an intermittent thing.

**Comment by thibaudgg** [comment]
Thanks @briangadoury, I opened an issue on DocumentUp repo: https://github.com/jeromegn/DocumentUp/issues/113
