### ISSUE TITLE
Show warnings

### ISSUE THREAD

**Issue by svoop** [guard/guard#979]
I've noticed my MiniTest suite throwing "warning: method redefined" at me when running with `rake`. Using guard, however, the warnings are suppressed and I don't see where this is configured or how this is happening.

The Rakefile has a setting for this:

```ruby
Rake::TestTask.new do |t|
  t.warning = true
end
```

RUBYOPT is set to the same value not including any `-W` – checked that in a unit test which issues a warning.

There's no such thing in Guardfile, can warnings be enabled at all? If not, why are they suppressed by default and would a PR be considered which adds a config similar to the one in Rake::TestTask?

**Comment by rymai** [comment]
I advise opening the issue in the relevant Guard plugin project. I'm going to close this issue for now. 🙏

**Comment by svoop** [comment]
Okidoke, thanks for the hint!
