### ISSUE TITLE
Incorrect homepage on Rubygems.org 

### ISSUE THREAD

**Issue by karnowski** [guard/guard#990]
On the RubyGems.org page for Guard:
https://rubygems.org/gems/guard

The "Homepage" link goes to:
https://guardgem.org/
_(Not your page!)_

But according to the gemspec it should go to:
https://guard.github.io/guard/

This looks like a config change on the RubyGems.org setup and not a code change.  (I thought Ruby Gems would read the value from the `guard.gemspec` file, but evidently that is incorrect?)

**Comment by campreb** [comment]
It looks like the change has been applied to the master branch (https://github.com/guard/guard/commit/a97713c0b5c861426fac1968cb7772c302e57c75), but there hasn't been a release lately to push the change to rubygems.org (here is the [gemspec](https://github.com/guard/guard/blob/v2.18.0/guard.gemspec) from the latest tagged release)

**Comment by rymai** [comment]
Fixed in 2.18.1, thanks! https://rubygems.org/gems/guard/versions/2.18.1
