### ISSUE TITLE
ostruct - notification of breaking change in Ruby 3.5.0

### ISSUE THREAD

**Issue by MatzFan** [guard/guard#992]
FYI running Guard with Ruby 3.3.5 results in a warning re the removal of `ostruct` from the Standard Library in Ruby 3.5.0.

```bash
/home/me/.rbenv/versions/3.3.5/lib/ruby/gems/3.3.0/gems/guard-2.18.1/lib/guard/cli.rb:5: warning: ostruct was loaded from the standard library, but will no longer be part of the default gems starting from Ruby 3.5.0.
You can add ostruct to your Gemfile or gemspec to silence this warning.
```
Looks like `ostruct` is loaded at [this line](https://github.com/guard/guard/blob/7ccce79c46a6e9d1acaca989bc1a2b72d3806221/lib/guard/dsl_describer.rb#L10).

The fix is suggested in the warning.

**Comment by rymai** [comment]
Fixed by https://github.com/guard/guard/pull/994.
